### ISSUE TITLE
Xamarin Forms support

### ISSUE THREAD

**Issue by sharpwood** [wieslawsoltes/Svg.Skia#10]
It prompts Operation is not supported on this platform when I load svg file .

**Comment by wieslawsoltes** [comment]
@sharpwood Could you provide version you have used? Please also provide stack trace.

This can be related to netstandard2.0 support and issue with SVG/System.Drawing dependency. I am waiting for updated SVG library that's probably will fix some of those issue if not all.

**Comment by sharpwood** [comment]
I used the last Svg.Skia version 0.6  
 .net standard 2.1  
SkiaSharp 1.68.1.1
 Xamarin Form 4.4  
@wieslawsoltes

**Comment by wieslawsoltes** [comment]
@sharpwood Do you have call stack from the exception?

**Comment by wieslawsoltes** [comment]
What platform are you targeting using Xamarin Forms?

**Comment by wieslawsoltes** [comment]
@sharpwood Trying to fix some issues https://github.com/vvvv/SVG/pull/635

**Comment by sharpwood** [comment]
I am using Xamarin Forms on Android 10.0 @wieslawsoltes

**Comment by sharpwood** [comment]
`01-09 08:12:32.338 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/user32.dll': '(null)'.
01-09 08:12:32.339 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.340 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.340 D/Mono    (19022): DllImport error loading library '/system/lib64/user32.dll': '(null)'.
01-09 08:12:32.340 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.340 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.341 D/Mono    (19022): DllImport error loading library 'user32.dll': 'dlopen failed: library "user32.dll" not found'.
01-09 08:12:32.342 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.343 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.344 D/Mono    (19022): DllImport error loading library 'user32.dll': 'dlopen failed: library "user32.dll" not found'.
01-09 08:12:32.345 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/user32': '(null)'.
01-09 08:12:32.345 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.so': '(null)'.
01-09 08:12:32.346 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.so': '(null)'.
01-09 08:12:32.346 D/Mono    (19022): DllImport error loading library '/system/lib64/user32': '(null)'.
01-09 08:12:32.346 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.so': '(null)'.
01-09 08:12:32.346 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.so': '(null)'.
01-09 08:12:32.347 D/Mono    (19022): DllImport error loading library 'user32': 'dlopen failed: library "user32" not found'.
01-09 08:12:32.347 D/Mono    (19022): DllImport error loading library 'libuser32.so': 'dlopen failed: library "libuser32.so" not found'.
01-09 08:12:32.348 D/Mono    (19022): DllImport error loading library 'libuser32.so': 'dlopen failed: library "libuser32.so" not found'.
01-09 08:12:32.349 D/Mono    (19022): DllImport error loading library 'user32': 'dlopen failed: library "user32" not found'.
01-09 08:12:32.349 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll': '(null)'.
01-09 08:12:32.350 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.351 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.351 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll': '(null)'.
01-09 08:12:32.351 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.351 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.352 D/Mono    (19022): DllImport error loading library 'libuser32.dll': 'dlopen failed: library "libuser32.dll" not found'.
01-09 08:12:32.353 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.354 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.354 D/Mono    (19022): DllImport error loading library 'libuser32.dll': 'dlopen failed: library "libuser32.dll" not found'.
01-09 08:12:32.355 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libMonoSupportW.so': '(null)'.
01-09 08:12:32.355 I/chatty  (19022): uid=10760(com.companyname) identical 1 line
01-09 08:12:32.356 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libMonoSupportW.so': '(null)'.
01-09 08:12:32.356 D/Mono    (19022): DllImport error loading library '/system/lib64/libMonoSupportW.so': '(null)'.
01-09 08:12:32.356 I/chatty  (19022): uid=10760(com.companyname) identical 1 line
01-09 08:12:32.356 D/Mono    (19022): DllImport error loading library '/system/lib64/libMonoSupportW.so': '(null)'.
01-09 08:12:32.357 D/Mono    (19022): DllImport error loading library 'libMonoSupportW.so': 'dlopen failed: library "libMonoSupportW.so" not found'.
01-09 08:12:32.358 I/chatty  (19022): uid=10760(com.companyname) identical 2 lines
01-09 08:12:32.359 D/Mono    (19022): DllImport error loading library 'libMonoSupportW.so': 'dlopen failed: library "libMonoSupportW.so" not found'.
01-09 08:12:32.359 W/Mono    (19022): DllImport unable to load library 'dlopen failed: library "libMonoSupportW.so" not found'.
01-09 08:12:32.359 D/Mono    (19022): DllImport attempting to load: 'gdi32.dll'.
01-09 08:12:32.360 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/gdi32.dll': '(null)'.
01-09 08:12:32.360 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.dll.so': '(null)'.
01-09 08:12:32.361 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.dll.so': '(null)'.
01-09 08:12:32.361 D/Mono    (19022): DllImport error loading library '/system/lib64/gdi32.dll': '(null)'.
01-09 08:12:32.361 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.dll.so': '(null)'.
01-09 08:12:32.361 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.dll.so': '(null)'.
01-09 08:12:32.362 D/Mono    (19022): DllImport error loading library 'gdi32.dll': 'dlopen failed: library "gdi32.dll" not found'.
01-09 08:12:32.363 D/Mono    (19022): DllImport error loading library 'libgdi32.dll.so': 'dlopen failed: library "libgdi32.dll.so" not found'.
01-09 08:12:32.364 D/Mono    (19022): DllImport error loading library 'libgdi32.dll.so': 'dlopen failed: library "libgdi32.dll.so" not found'.
01-09 08:12:32.364 D/Mono    (19022): DllImport error loading library 'gdi32.dll': 'dlopen failed: library "gdi32.dll" not found'.
01-09 08:12:32.366 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/gdi32': '(null)'.
01-09 08:12:32.366 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.so': '(null)'.
01-09 08:12:32.367 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.so': '(null)'.
01-09 08:12:32.367 D/Mono    (19022): DllImport error loading library '/system/lib64/gdi32': '(null)'.
01-09 08:12:32.367 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.so': '(null)'.
01-09 08:12:32.367 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.so': '(null)'.
01-09 08:12:32.368 D/Mono    (19022): DllImport error loading library 'gdi32': 'dlopen failed: library "gdi32" not found'.
01-09 08:12:32.368 D/Mono    (19022): DllImport error loading library 'libgdi32.so': 'dlopen failed: library "libgdi32.so" not found'.
01-09 08:12:32.369 D/Mono    (19022): DllImport error loading library 'libgdi32.so': 'dlopen failed: library "libgdi32.so" not found'.
01-09 08:12:32.370 D/Mono    (19022): DllImport error loading library 'gdi32': 'dlopen failed: library "gdi32" not found'.
01-09 08:12:32.370 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.dll': '(null)'.
01-09 08:12:32.371 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.dll.so': '(null)'.
01-09 08:12:32.371 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libgdi32.dll.so': '(null)'.
01-09 08:12:32.371 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.dll': '(null)'.
01-09 08:12:32.371 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.dll.so': '(null)'.
01-09 08:12:32.371 D/Mono    (19022): DllImport error loading library '/system/lib64/libgdi32.dll.so': '(null)'.
01-09 08:12:32.372 D/Mono    (19022): DllImport error loading library 'libgdi32.dll': 'dlopen failed: library "libgdi32.dll" not found'.
01-09 08:12:32.373 D/Mono    (19022): DllImport error loading library 'libgdi32.dll.so': 'dlopen failed: library "libgdi32.dll.so" not found'.
01-09 08:12:32.374 D/Mono    (19022): DllImport error loading library 'libgdi32.dll.so': 'dlopen failed: library "libgdi32.dll.so" not found'.
01-09 08:12:32.374 D/Mono    (19022): DllImport error loading library 'libgdi32.dll': 'dlopen failed: library "libgdi32.dll" not found'.
01-09 08:12:32.374 W/Mono    (19022): DllImport unable to load library 'dlopen failed: library "libgdi32.dll" not found'.
01-09 08:12:32.374 D/Mono    (19022): DllImport attempting to load: 'user32.dll'.
01-09 08:12:32.375 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/user32.dll': '(null)'.
01-09 08:12:32.375 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.376 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.376 D/Mono    (19022): DllImport error loading library '/system/lib64/user32.dll': '(null)'.
01-09 08:12:32.376 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.376 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.377 D/Mono    (19022): DllImport error loading library 'user32.dll': 'dlopen failed: library "user32.dll" not found'.
01-09 08:12:32.378 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.378 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.379 D/Mono    (19022): DllImport error loading library 'user32.dll': 'dlopen failed: library "user32.dll" not found'.
01-09 08:12:32.380 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/user32': '(null)'.
01-09 08:12:32.380 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.so': '(null)'.
01-09 08:12:32.380 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.so': '(null)'.
01-09 08:12:32.381 D/Mono    (19022): DllImport error loading library '/system/lib64/user32': '(null)'.
01-09 08:12:32.381 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.so': '(null)'.
01-09 08:12:32.381 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.so': '(null)'.
01-09 08:12:32.381 D/Mono    (19022): DllImport error loading library 'user32': 'dlopen failed: library "user32" not found'.
01-09 08:12:32.382 D/Mono    (19022): DllImport error loading library 'libuser32.so': 'dlopen failed: library "libuser32.so" not found'.
01-09 08:12:32.383 D/Mono    (19022): DllImport error loading library 'libuser32.so': 'dlopen failed: library "libuser32.so" not found'.
01-09 08:12:32.383 D/Mono    (19022): DllImport error loading library 'user32': 'dlopen failed: library "user32" not found'.
01-09 08:12:32.384 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll': '(null)'.
01-09 08:12:32.384 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.385 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libuser32.dll.so': '(null)'.
01-09 08:12:32.385 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll': '(null)'.
01-09 08:12:32.385 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.385 D/Mono    (19022): DllImport error loading library '/system/lib64/libuser32.dll.so': '(null)'.
01-09 08:12:32.386 D/Mono    (19022): DllImport error loading library 'libuser32.dll': 'dlopen failed: library "libuser32.dll" not found'.
01-09 08:12:32.386 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.387 D/Mono    (19022): DllImport error loading library 'libuser32.dll.so': 'dlopen failed: library "libuser32.dll.so" not found'.
01-09 08:12:32.388 D/Mono    (19022): DllImport error loading library 'libuser32.dll': 'dlopen failed: library "libuser32.dll" not found'.
01-09 08:12:32.388 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libMonoSupportW.so': '(null)'.
01-09 08:12:32.389 I/chatty  (19022): uid=10760(com.companyname) identical 1 line
01-09 08:12:32.389 D/Mono    (19022): DllImport error loading library '/storage/emulated/0/Android/data/com.companyname/files/.__override__/libMonoSupportW.so': '(null)'.
01-09 08:12:32.389 D/Mono    (19022): DllImport error loading library '/system/lib64/libMonoSupportW.so': '(null)'.
01-09 08:12:32.389 I/chatty  (19022): uid=10760(com.companyname) identical 1 line
01-09 08:12:32.389 D/Mono    (19022): DllImport error loading library '/system/lib64/libMonoSupportW.so': '(null)'.
01-09 08:12:32.390 D/Mono    (19022): DllImport error loading library 'libMonoSupportW.so': 'dlopen failed: library "libMonoSupportW.so" not found'.
01-09 08:12:32.391 I/chatty  (19022): uid=10760(com.companyname) identical 2 lines
01-09 08:12:32.392 D/Mono    (19022): DllImport error loading library 'libMonoSupportW.so': 'dlopen failed: library "libMonoSupportW.so" not found'.
01-09 08:12:32.392 W/Mono    (19022): DllImport unable to load library 'dlopen failed: library "libMonoSupportW.so" not found'.
01-09 08:12:32.390 W/(19022): type=1400 audit(0.0:7016113): avc: granted { write } for pid=19022 name=E6A38BE79B982E737667 dev="sdcardfs" ino=194215 scontext=u:r:untrusted_app:s0:c248,c258,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=file
01-09 08:12:32.432 I/.bigdipperches(19022): Explicit concurrent copying GC freed 17171(1076KB) AllocSpace objects, 22(704KB) LOS objects, 59% free, 4114KB/10MB, paused 30us total 18.189ms
01-09 08:12:32.434 D/Mono    (19022): GC_TAR_BRIDGE bridges 255 objects 36997 opaque 14548 colors 247 colors-bridged 247 colors-visible 247 xref 16 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.03ms tarjan 8.13ms scc-setup 0.04ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.65ms
01-09 08:12:32.434 D/Mono    (19022): GC_BRIDGE: Complete, was running for 20.02ms
01-09 08:12:32.434 D/Mono    (19022): GC_MINOR: (Nursery full) time 18.09ms, stw 18.63ms promoted 2020K major size: 20848K in use: 19425K los size: 16784K in use: 15620K
01-09 08:12:32.436 D/Mono    (19022): GC_TAR_BRIDGE bridges 0 objects 0 opaque 0 colors 0 colors-bridged 0 colors-visible 247 xref 16 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.03ms tarjan 8.13ms scc-setup 0.04ms gather-xref 0.00ms xref-setup 0.00ms cleanup 0.00ms
01-09 08:12:32.437 D/Mono    (19022): GC_BRIDGE: Complete, was running for 0.04ms
01-09 08:12:32.437 D/Mono    (19022): GC_MINOR: (Concurrent start) time 0.74ms, stw 2.88ms promoted 0K major size: 20848K in use: 19425K los size: 16784K in use: 15620K
01-09 08:12:32.437 D/Mono    (19022): GC_MAJOR_CONCURRENT_START: (LOS overflow)
**System.PlatformNotSupportedException:** 'Operation is not supported on this platform.'
`

**Comment by wieslawsoltes** [comment]
@sharpwood Seems like GDI+ issue. Trying to fix this in SVG library.

Still I need to test this on Xamarin Forms for Android.

**Comment by wieslawsoltes** [comment]
@sharpwood Could you try newly released version `0.0.8` and check if it fixes your issue?

**Comment by sharpwood** [comment]
I tested 0.09 and 0.10 ,it still not works .        Svg.Picture is null after load svg file.

**Comment by zoli13** [comment]
I tried with 0.1.5, and same issue, Picture is NULL, because svg.Load(stream) fails, I can see in output:

`02-26 21:54:32.350 D/Mono    (26357): Loading reference 1 of System.Xml.dll asmctx DEFAULT, looking for System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e`
`02-26 21:54:32.350 D/Mono    (26357): Assembly Ref addref System.Xml[0xdf9884e0] -> System[0xd437a8c0]: 7`
`[0:] base.apk Error: 0 : `
`[0:] Exception has been thrown by the target of an invocation.`
`[0:] base.apk Error: 0 : `
`[0:] The CreateDocument method can only be used to parse root <svg> elements.`
`[0:] base.apk Error: 0 : `
`[0:] The CreateDocument method can only be used to parse root <svg> elements.`
`[0:] base.apk Error: 0 : `
`[0:] The CreateDocument method can only be used to parse root <svg> elements.`
`[0:] base.apk Error: 0 : `
` .... `

**Comment by wieslawsoltes** [comment]
@zoli13 Can you provide sample SVG file that is causing this issue?

**Comment by zoli13** [comment]
This one: https://github.com/mono/SkiaSharp.Extended/files/4258056/opacity.zip

**Comment by wieslawsoltes** [comment]
> I load it as stream of embedded resource - if that matters.

Maybe this is causing the issue. Could you try loading from string or a file? Maybe try rewinding embedded resource stream to position 0 (`stream.Position = 0;`) ?

**Comment by wieslawsoltes** [comment]
@zoli13 On windows it works
![SvgToPng_2020-02-26_23-15-36](https://user-images.githubusercontent.com/2297442/75393242-eb83d380-58ed-11ea-9183-86b71f6c3421.png)

**Comment by zoli13** [comment]
Sample project attached, just run the Android (I tried on Emulator), and you will see.
[svg.zip](https://github.com/wieslawsoltes/Svg.Skia/files/4260238/svg.zip)

**Comment by wieslawsoltes** [comment]
@zoli13 Could you try running this code and check Debug output, I have issues running Android projects on my machine.
```C#
	// Learn more about making custom code visible in the Xamarin.Forms previewer
	// by visiting https://aka.ms/xamarinforms-previewer
	[DesignTimeVisible(false)]
	public partial class MainPage : ContentPage
	{
		public MainPage()
		{
			InitializeComponent();
		}
void Print(Exception ex)
{
Debug.WriteLine(ex.Message);
Debug.WriteLine(ex.StackTrace);
if (ex.InnerException != null)
    Print(ex.InnerException);
}
		private void _SKCanvasViewMenu_PaintSurface(object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs e)
		{
			var canvas = e.Surface.Canvas;

			canvas.Clear(Color.White.ToSKColor());

try
{
			Svg.Skia.SKSvg svg = new Svg.Skia.SKSvg();
			using (var stream = this.GetType().Assembly.GetManifestResourceStream("svg.Resources.2.svg"))
                        {
Debug.WriteLine("stream.Position=" + stream.Position.ToString());
				svg.Load(stream);
                        }
			canvas.DrawPicture(svg.Picture);
}
catch (Exception ex)
{
Print(ex);
}
		}

		private void _SKCanvasViewMenu_Touch(object sender, SkiaSharp.Views.Forms.SKTouchEventArgs e)
		{
			_SKCanvasViewMenu.InvalidateSurface();
		}
	}
```

**Comment by zoli13** [comment]
The exception is coming from `canvas.DrawPicture(svg.Picture);` , because Picture is NULL. So nothing useful info in the exception.

`[0:] Value cannot be null.`
`Parameter name: picture`
`[0:]   at SkiaSharp.SKCanvas.DrawPicture (SkiaSharp.SKPicture picture, SkiaSharp.SKPaint paint) [0x00003] in <718f8bdc6f3b41159baabdd0a10b4739>:0` 
`  at svg.MainPage._SKCanvasViewMenu_PaintSurface (System.Object sender, SkiaSharp.Views.Forms.SKPaintSurfaceEventArgs e) [0x00050] in MainPage.xaml.cs:42 `

And `stream.Position=0`

The Load() call traces some error, I attached the full output.
[svg_load_trace.zip](https://github.com/wieslawsoltes/Svg.Skia/files/4260552/svg_load_trace.zip)

**Comment by wieslawsoltes** [comment]
@zoli13 I need to debug this on my machine, but first I need to fix Android emulator deployment as it's broken on my laptop.

**Comment by 15mgm15** [comment]
@wieslawsoltes  By any chance did you had a chance to review this issue?

**Comment by gsgou** [comment]
[svg.zip](https://github.com/wieslawsoltes/Svg.Skia/files/9376816/svg.zip)
Updated the project libs and seems to work now
