### ISSUE TITLE
SVG issue with Avalonia UI on Raspberry Pi

### ISSUE THREAD

**Issue by Wasenshi123** [wieslawsoltes/Svg.Skia#102]
Hi,

I have created an avalonia app and intended to use it primarily on Raspberry pi.  I use svg for the logo. So I use Avalonia.Svg.Skia Nuget package

When I test it on my RPi, the svg is not showing correctly (see the picture)
<img width="470" alt="Window" src="https://user-images.githubusercontent.com/12524716/157451017-c4d524e7-fb87-44a5-9141-c249c9d24793.png">
On Windows

<img width="302" alt="RPi" src="https://user-images.githubusercontent.com/12524716/157451066-bd369911-486b-482d-b716-e298ad77090d.png">
On RPi 3B+

**Platform:** Raspberry Pi 3 Model B+
**OS:** Raspberry Pi OS (Bullseye)
**Package version:** Avalonia.Svg.Skia 0.10.10
**Avalonia version:** 0.10.10

**Comment by wieslawsoltes** [comment]
Try adding those lines to your program 
https://github.com/wieslawsoltes/Svg.Skia/blob/d31efcb99eed70ed7d4671035007c046a5e1a9f3/samples/AvaloniaSvgSample/Program.cs#L19-L21
