### ISSUE TITLE
Arabic Text Rendering Issue

### ISSUE THREAD

**Issue by fredmeister77** [wieslawsoltes/Svg.Skia#104]
Hello,

I am using SVG.Skia as a nuget package to render some arabic fonts in SVG.

I was running into the same issue reported here:
https://social.msdn.microsoft.com/Forums/en-US/5d88c41b-8766-4211-8ae2-ad769dadbed3/draw-arabic-text-using-skiasharp?forum=xamarinforms

Where HarfBuzz is recommended.

I noticed that HarfBuzz is used in SVG.Skia, and the SKShaper from it is only used when a preprocessor constant is present, USE_TEXT_SHAPER here (and below it):
https://github.com/wieslawsoltes/Svg.Skia/blob/13899926b009b4c65e5e1d73e49a22d434c7453e/src/Svg.Model/Drawables/Elements/TextDrawable.cs#L270

I apologize for my ignorance, but this presents a few questions for me: 
1. Is it true that given that this constant is not present, the shaper code will never be called in the nuget package?
2. Is the intention that we should build the project ourselves with the constant defined if we need to use HarfBuzz?
3. Is there another way I am not aware of to use the package and specify when I want to use the SKShaper?

I'd be happy to update the project and make this an API option vs. Preprocessor and submit a PR, but I'm concerned I don't know enough about the project, codebase or intention behind USE_TEXT_SHAPER to do it properly.

Thanks for your time.

**Comment by wieslawsoltes** [comment]
Test rendering support is very basic and currently no plans of adding more advanced features.
