### ISSUE TITLE
Avalonia control change color

### ISSUE THREAD

**Issue by tommaier123** [wieslawsoltes/Svg.Skia#105]
Hello,
I'm using the Avalonia control to display buttons. Currently I switch between multiple SVGs with highlighted/disabled color.
I want to add styling so I would need to dynamically change the color. Is there a way to do that?

**Comment by Ben290182** [comment]
I was wondering the same thing. I could not find a way to do it with this library, so instead I manually copied the path data from the SVG into an Avalonia Path object. Then you can set the Fill and Stroke.

**Comment by tommaier123** [comment]
Great suggestion. I can easily export the XAML path from Inkscape.

**Comment by wieslawsoltes** [comment]
Please use https://github.com/wieslawsoltes/SvgToXaml
