### ISSUE TITLE
'System.AccessViolationException' occurred in SkiaSharp.dll - Possible issue with SKSvg method "load"

### ISSUE THREAD

**Issue by RamenStudios** [wieslawsoltes/Svg.Skia#107]
Hello, 
I am _very much_ a C# novice, currently trying to develop a WPF desktop application in VS2022. Without going into too much detail, the application needs to be capable of opening and displaying SVG files while maintaining the path data. 
I created the following method to open and display the desired image:
`
       private void draw(string path, SKCanvas canvas)
        {

            var svg = new SKSvg();

            svg.Load(path);

            if(svg.Picture != null)
            {
                canvas.DrawPicture(svg.Picture);
            }
            else
            {
                System.Windows.MessageBox.Show("Picture load fail");
            }
            
        }
`
The program breaks at the draw line with the exception in the title. The following provides more information:
![image](https://user-images.githubusercontent.com/97457051/170888448-a94268aa-7750-4e93-9ccc-f2056960fb83.png)

I attempted to use `svg.FromSvg(path)` instead, to which I received the error: System.Xml.XmlException
  Message=Data at the root level is invalid. Line 1, position 1.
  Source=System.Private.Xml
 
From the little I know, this seems to indicate an issue with the Load and FromSvg methods not being able to parse the given SVG file. I am wondering if this is simply a limitation of SKSvg, an issue on my end, or an issue with the library?

**Comment by wieslawsoltes** [comment]
Looks like your svg file has invalid xml, can you post the svg file contents here?

**Comment by wieslawsoltes** [comment]
No sample svg
