### ISSUE TITLE
Setting the marker twice renders wrong path

### ISSUE THREAD

**Issue by kristofferjalen** [wieslawsoltes/Svg.Skia#108]
Given these two paths:

```
<g>
   <path d="M0 0 L40 0 M50 0 M50 0 L90 0" stroke-width="10" style="stroke:black;" transform="translate(0, 75)" />
   <path d="M0 0 L40 0 M50 0 L90 0" stroke-width="10" style="stroke:black;" transform="translate(0, 120)" />
</g>
```
On https://www.svgviewer.dev/ and with `SkiaSharp.Extended.Svg.SKSvg` both these paths are rendered as two horizontal lines with space in-between:

![image](https://user-images.githubusercontent.com/2280252/171851246-bb9d92d2-75f3-47b5-826b-173499e4d996.png)

But with `Svg.Skia` the first path is rendered as a single line only:

![image](https://user-images.githubusercontent.com/2280252/171851492-26e8821e-aeec-49a9-9c20-3c4859585d4f.png)

I realize the first path sets the marker twice, `M50 0`, but is that a problem?

**Comment by wieslawsoltes** [comment]
The first path is invalid
![image](https://user-images.githubusercontent.com/2297442/202897708-8de13f3f-fc8a-4786-aa82-42fa686d2063.png)
