### ISSUE TITLE
CustomTypefaceProvider can't match font family

### ISSUE THREAD

**Issue by skaman** [wieslawsoltes/Svg.Skia#109]
I stumbled in a problem where CustomTypefaceProvider can't match the family name from an SVG with the one registered.

The problem is this line:
https://github.com/wieslawsoltes/Svg.Skia/blob/f5ced19d5476d250d1aa7558bc26b0ccbb0652ea/src/Svg.Skia/TypefaceProviders/CustomTypefaceProvider.cs#L47

The condition should be:
```c#
if (fontFamilyName == FamilyName)
```

otherwise it ignore family with quotes or multiple families

**Comment by wieslawsoltes** [comment]
You can set your own providers with specified rules.

**Comment by dpollock** [comment]
This needs to be re-opened as @skaman is correct. 
![image](https://user-images.githubusercontent.com/1530315/201143108-c22e363d-f540-42f3-9305-8492fd607f9b.png)

We're splitting the fontFamilyNames and looping through each of them but then not using 'fontFamilyName' for the comparison. We're still comparing it to the original list of family names. Which means this only works if the original list has just one font listed.

I can create a pull-request for the correction.

**Comment by dpollock** [comment]
In the meantime, for my own code, I've copied the CustomTypefaceProvider class and made the correction as you suggested.

**Comment by dpollock** [comment]
Actually this particular code issue appears to be corrected in the 0.6.0-preview3
