### ISSUE TITLE
Avalonia 0.10.16 support

### ISSUE THREAD

**Issue by GNUGradyn** [wieslawsoltes/Svg.Skia#111]
Avalonia 0.10.14 is currently the latest supported version. Update to 0.10.16
![image](https://user-images.githubusercontent.com/20762604/184273868-4ae439d8-bfcc-4747-9c01-c23360da59d4.png)

**Comment by wieslawsoltes** [comment]
Not true, 0.10.16 is supported and released https://www.nuget.org/packages/Avalonia.Svg.Skia/0.10.16#dependencies-body-tab

**Comment by wieslawsoltes** [comment]
Also 0.10.14 is compatible with 0.10.16, you just need to fix nuget references by directly referencing correct package version as the error is telling.
