### ISSUE TITLE
UWP support

### ISSUE THREAD

**Issue by jrc14** [wieslawsoltes/Svg.Skia#12]
What is the state of support for UWP in Svg.Skia?  I'm finding that it works for simple SVG content, but for more complex SVG, I am getting PlatformNotSupportedException: System.Drawing is not supported on this platform. (inner exception "The type initializer for 'Svg.SvgElement' threw an exception.").  This is the stack trace:
```
   at System.RuntimeFieldHandle.SetValue(RtFieldInfo field, Object obj, Object value, RuntimeType fieldType, FieldAttributes fieldAttr, RuntimeType declaringType, Boolean& domainInitialized)
   at System.Reflection.RtFieldInfo.InternalSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture, StackCrawlMark& stackMark)
   at System.Reflection.RtFieldInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at Svg.Skia.UseDrawable..ctor(SvgUse svgUse, SKRect skOwnerBounds, Boolean ignoreDisplay)
   at Svg.Skia.DrawableFactory.Create(SvgElement svgElement, SKRect skOwnerBounds, Boolean ignoreDisplay)
   at Svg.Skia.FragmentDrawable..ctor(SvgFragment svgFragment, SKRect skOwnerBounds, Boolean ignoreDisplay)
   at Svg.Skia.DrawableFactory.Create(SvgElement svgElement, SKRect skOwnerBounds, Boolean ignoreDisplay)
   at Svg.Skia.SKSvg.ToPicture(SvgFragment svgFragment)
   at Svg.Skia.SKSvg.FromSvg(String svg)
```
and this is the code that produced this problem:

```
    svgText = "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"  width=\"100px\" height=\"300x\">" +
     "<defs>" +
     "<path id=\"gl1536\" d=\"M 10 1 C 7 2 7 4 7 7 C 7 8 7 10 7 11 C 11 11 15 13 20 13 C 33 14 34 14 34 17 C 34 18 34 71 34 131 C 34 169 34 205 34 243 C 30 243 26 243 21 243 C 7 245 4 246 5 250 C 5 252 5 253 5 255 C 37 255 69 255 101 255 C 182 256 197 255 198 253 C 200 253 201 243 203 233 C 203 224 204 210 205 201 C 208 188 208 187 205 185 C 198 179 191 185 188 201 C 188 203 187 207 187 208 C 185 210 184 216 181 221 C 179 227 178 234 176 237 C 175 240 175 242 174 245 C 158 245 142 243 126 243 C 72 243 72 243 69 233 C 66 224 68 21 69 17 C 71 14 72 13 82 13 C 95 13 101 11 101 7 C 101 5 100 2 98 2 C 97 1 15 1 10 1 z\" fill=\"red\"/> </defs>" +
     "<use xlink:href=\"#gl1536\" x=\"0\" y=\"0\"/>" +
     "</svg>";
    using(SKSvg svg=new SKSvg())
    {
        SKPicture pic = svg.FromSvg(svgText);
    }
```

I'm not sure whether I should expect this to fail in UWP because it's not supported.  But ideally it would be support(i.e. Svg.Skia would be avoiding calling the System.Drawing library, which is not available in UWP, and would be calling the correct Skia functions).  Or if that isn't possible, could we have a less hostile behaviour in the places where Svg.Skia does end up calling System.Drawing - such as not throwing an exception (but instead, simply not drawing the unsupported SVG content).

Thanks for your attention - and if I can help further, please point me at what I need to do.

**Comment by wieslawsoltes** [comment]
I will check the UWP, but first there seems to be error in SVG: `height="300px"` not `height="300x"`
```C#
    svgText = "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\"  width=\"100px\" height=\"300px\">" +
     "<defs>" +
     "<path id=\"gl1536\" d=\"M 10 1 C 7 2 7 4 7 7 C 7 8 7 10 7 11 C 11 11 15 13 20 13 C 33 14 34 14 34 17 C 34 18 34 71 34 131 C 34 169 34 205 34 243 C 30 243 26 243 21 243 C 7 245 4 246 5 250 C 5 252 5 253 5 255 C 37 255 69 255 101 255 C 182 256 197 255 198 253 C 200 253 201 243 203 233 C 203 224 204 210 205 201 C 208 188 208 187 205 185 C 198 179 191 185 188 201 C 188 203 187 207 187 208 C 185 210 184 216 181 221 C 179 227 178 234 176 237 C 175 240 175 242 174 245 C 158 245 142 243 126 243 C 72 243 72 243 69 233 C 66 224 68 21 69 17 C 71 14 72 13 82 13 C 95 13 101 11 101 7 C 101 5 100 2 98 2 C 97 1 15 1 10 1 z\" fill=\"red\"/> </defs>" +
     "<use xlink:href=\"#gl1536\" x=\"0\" y=\"0\"/>" +
     "</svg>";
    using(SKSvg svg=new SKSvg())
    {
        SKPicture pic = svg.FromSvg(svgText);
    }
```

**Comment by wieslawsoltes** [comment]
I have worked on UWP support and tried to eliminate all unsupported System.Drawing calls, but there may be some cornet case, so please report any issue to I can fix them.

**Comment by jrc14** [comment]
Thanks for the answer - you're quite right; when pasting in the code, I did manage to edit 'px' into 'x'.  But even using the corrected source code you supplied, I am seeing that PlatformNotSupportedException.  Do you need more information about this repro case?

**Comment by wieslawsoltes** [comment]
> Thanks for the answer - you're quite right; when pasting in the code, I did manage to edit 'px' into 'x'. But even using the corrected source code you supplied, I am seeing that PlatformNotSupportedException. Do you need more information about this repro case?

No I have all the info I need. I can repro the issue on my machine. I will try to fix, but there seems to be some bigger issue in Svg lib on UWP. I will at least add some try/catch block for affected part. This is related to how Svg library is handling Use element. I have some hack to get it working with SkiaSharp and this hack is using reflection to get stuff working.

**Comment by wieslawsoltes** [comment]
For reference:
```
   at System.Drawing.Text.PrivateFontCollection..ctor()
   at Svg.SvgElement..cctor() in C:\DOWNLOADS\GitHub\Svg.Skia\externals\SVG\Source\SvgElementStyle.cs:line 421
```

**Comment by wieslawsoltes** [comment]
For now I have suppressed the exception https://github.com/wieslawsoltes/Svg.Skia/commit/6fac9d8247f9a208da0c53059d114636fe40688b until better fix is found.
