### ISSUE TITLE
Exception thrown on iOS: `Attempting to JIT compile method void Svg.Skia.SkiaModelExtensions:Draw`

### ISSUE THREAD

**Issue by charlesroddie** [wieslawsoltes/Svg.Skia#125]
Exception thrown on iOS. App center crash report (crashes every time).
```
Attempting to JIT compile method 'void Svg.Skia.SkiaModelExtensions:Draw (ShimSkiaSharp.CanvasCommand,SkiaSharp.SKCanvas)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
at Svg.Skia.SkiaModelExtensions.Draw (ShimSkiaSharp.SKPicture picture, SkiaSharp.SKCanvas skCanvas) <0x103b337d0 + 0x00098> in <b7c52603efd34af68bf2da1b58fb1fa9#49559fcfbc349f22625271efb8dd0e18>:0
at Svg.Skia.SkiaModelExtensions.ToSKPicture (ShimSkiaSharp.SKPicture picture) <0x103b2f010 + 0x0011b> in <b7c52603efd34af68bf2da1b58fb1fa9#49559fcfbc349f22625271efb8dd0e18>:0
at Svg.Skia.SKSvg.FromSvg (System.String svg) <0x103b33a20 + 0x000ab> in <b7c52603efd34af68bf2da1b58fb1fa9#49559fcfbc349f22625271efb8dd0e18>:0
...
```

We just did an update of the Svg.Skia Nuget from 0.5.10 to 0.5.16 and this issue was probably caused somewhere in between. Confirming this now. Hopefully we can also confirm the version increment that caused the issue.

**Comment by wieslawsoltes** [comment]
Can you try version 6 preview?

**Comment by charlesroddie** [comment]
So far:

0.5.10: works
0.5.16: doesn't work
0.6.0-preview1: doesn't work

We can try to bifurcate to get the first version that fails, and also I see 0.6.0-preview2 is out. An ios testflight release takes half an hour, so which is more helpful to check first?

**Comment by wieslawsoltes** [comment]
I am not sure, if you can try first 0.6.0-preview2, but most helpful would which version introduced the issue what what part of code. I can't really test that issue on my hardware.

**Comment by charlesroddie** [comment]
I don't see anything problematic in the diff
https://github.com/wieslawsoltes/Svg.Skia/compare/0.5.11...0.5.11.1
So this may be a mono bug.
We will stick with 0.5.11 and test again when we can move our ios app to dotnet7.

**Comment by wieslawsoltes** [comment]
Might be target framework changes I guess

**Comment by charlesroddie** [comment]
I do often find that the mono mac/ios AOT compiler fails for its own reasons on perfectly good code, unlike netnative (and presumably NativeAOT) which tend to pick out bad code.

I'll close this since there isn't any current evidence of a problem caused by any code here.

**Comment by Rippletank** [comment]
Just found this after debugging basically same issue. Adding this in case it helps to identify the issue at any point. 

Difference is that I am using a local mac with simulator. I can confirm that the error appears when changing from 0.5.11 to 0.5.11.1 but not at compile time. The error appears on first run of Load(from stream) of an already created SKSvg object. It only occurs for IOS and not for android or UWP from a shared dll project (.net standard 2.0) that contains the only reference to Skiasharp and SKSvg.

The error message is "Method not found: SkiaSharp.SKTextBlob SkiaSharp.SKTextBlob.CreatePositioned(string,SkiaSharp.SKFont,System.ReadOnlySpan`1<SkiaSharp.SKPoint>)"


There appears to be a bug referenced, without much detail, at [https://github.com/mono/SkiaSharp/issues/2147](url)

I also can confirm that the work around is to stay on 0.5.11 but obviously this is feels a bit brittle.

**Comment by MartinZikmund** [comment]
To whoever hits this, we encountered this issue on Uno Platform and the root cause of this is the fact that `SkiaSharp` in .NET Standard 2.0 references `System.Memory` in a different version and that version mismatch causes issues with `ReadOnlySpan`. The workaround is to add the following targets to the iOS `.csproj`:

```xml
<Target Name="VSMac_RemoveSystemMemory" BeforeTargets="ResolveAssemblyReferences">
  <ItemGroup>
    <_ReferenceToRemove Include="@(Reference)" Condition="'%(Reference.Identity)'=='System.Memory'" />
    <Reference Remove="@(_ReferenceToRemove)" />
    <Reference Include="System.Memory" />
  </ItemGroup>
</Target>

<Target Name="VS_RemoveSystemMemory" BeforeTargets="FindReferenceAssembliesForReferences">
  <ItemGroup>
    <_ReferencePathToRemove Include="@(ReferencePath)" Condition="'%(ReferencePath.NuGetPackageId)'=='System.Memory'" />
    <ReferencePath Remove="@(_ReferencePathToRemove)" />
  </ItemGroup>
</Target>
```

**Comment by Rippletank** [comment]
Thank you! 

Can confirm this allows using version 0.5.18 without the missing method issue. The latest preview releases (0.6.0-preview5) also doesn't have the issue.
