### ISSUE TITLE
Colors when drawing onto SKSvgCanvas

### ISSUE THREAD

**Issue by samirem** [wieslawsoltes/Svg.Skia#128]
I am drawing the `SKPicture` onto an `SKSvgCanvas` through `canvas.DrawPicture(svg.Picture)`, but my stroke and fill colors all turn out black. Is it possible to preserve the colors from the original svg file?

**Comment by wieslawsoltes** [comment]
Can you post original svg and resulting drawing?

**Comment by wieslawsoltes** [comment]
No svg to reproduce
