### ISSUE TITLE
Providing additional fonts for Svg.Skia

### ISSUE THREAD

**Issue by jrc14** [wieslawsoltes/Svg.Skia#13]
I'm trying to use Svg.Skia with SVG content that is packaged (in an EPUB archive in fact) alongside font files - which should be used to supplement the system fonts that SKTypeFace.FromFamilyName knows about.  Do you have any thoughts about how this could be handled in Svg.Skia?

I have in mind to create a fork of the code, adding a mechanism that would let me feed in an object (I'd define ITypefaceProvider, with a method GetFontFamily(fontFamilyName, fontWeight, fontWidth, fontStyle) or something) which would let me specify an additional place that the code in SvgTextExtensions.SetTypeface could look for fonts.  But before doing any such thing, I thought I might ask (1) is there already some neat mechanism in place for doing this, and I am just too dumb to notice? (2) do you have any guidance to offer as to how I might make the changes, so that they would fit into your design philosophy for the library? - hoping that I might be able to produce a solution that you'd be able pull into the library.

**Comment by wieslawsoltes** [comment]
I did not run into this problem. We can come up with some solution together. No need for making forked version. I just have to figure out how to make the library plug-able.

**Comment by wieslawsoltes** [comment]
@jrc14 I will add interface in next release:
```C#
public interface ITypefaceProvider
{
    SKTypeface? FromFamilyName(string fontFamily, SKFontStyleWeight fontWeight, SKFontStyleWidth fontWidth, SKFontStyleSlant fontStyle);
}
```

You can implement your own typeface provider and add to `SvgTextExtensions.s_typefaceProviders`.

Change is already in `master` branch https://github.com/wieslawsoltes/Svg.Skia/commit/cb51079466b79dbd92d6afe8da4f6b218d996c9a

**Comment by jrc14** [comment]
Thank you - that looks good!

**Comment by JonathanDDuncan** [comment]
For the following example, how would I use ITypefaceProvider
`  public void SVGtoPNG(string id, string svg)
        {
             using (var skSVG = new SKSvg())
            {
                if (skSVG.FromSvg(svg) != null)
                {
                    using (var stream = File.OpenWrite(@"image.png")))
                    {
                        skSVG.Picture.ToImage(stream, SKColors.Empty,
                            SKEncodedImageFormat.Png, 100, 1f, 1f, SKColorType.Rgba8888, SKAlphaType.Premul);
                   }
                }
            }
        }`


We are using embeded fonts in our SVGs like this.
`<defs xmlns="http://www.w3.org/2000/svg">
    <style>

       @font-face {
                        font-family: Fontania;
                        src: url('data:application/font-woff;base64,d09GRgABAAAA....ysKzC/wZ21h')
                    }

    </style>
  </defs>`

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes
> For the following example, how would I use ITypefaceProvider
> ` public void SVGtoPNG(string id, string svg) { using (var skSVG = new SKSvg()) { if (skSVG.FromSvg(svg) != null) { using (var stream = File.OpenWrite(@"image.png"))) { skSVG.Picture.ToImage(stream, SKColors.Empty, SKEncodedImageFormat.Png, 100, 1f, 1f, SKColorType.Rgba8888, SKAlphaType.Premul); } } } }`
> 
> We are using embeded fonts in our SVGs like this.
> `
> <style>
> 
> ```
>    @font-face {
>                     font-family: Fontania;
>                     src: url('data:application/font-woff;base64,d09GRgABAAAA....ysKzC/wZ21h')
>                 }
> 
> </style>
> ```
> 
> `

This is not supported.

**Comment by JonathanDDuncan** [comment]
@wieslawsoltes Thanks for your prompt response

**Comment by jrc14** [comment]
@JonathanDDuncan It is doable (for my application, I have done it).  But it's not simple.

Essentially you'll need to create a separate utility class that parses the SVG file, finds places where "@font-face { whatever}" appears in it, and where it finds  src: url('...') it reads that source data and constructs an SKTypeFace from it, and adds it to a Dictionary<string,SKTypeFace>, that lets you obtain the typeface you want, based on its name.

Then you define a 'provider' class that implements ITypeFaceProvider, and in your code you construct an instance of your provider class., and register it by calling SKSvgSettings.s_typefaceProviders.Insert(0, myProviderInstance).

Your provider class has to implement a method FromFamilyName(string name, SKFontStyleWeight wt, SKFontStyleWidth dw, SKFontStyleSlant sl) which will use 'name' to do a look up the SKTypeface in your Dictionary<string,SKTypeFace>, do whatever messing about is necessary to apply weight, width and slant, and will then return the SKTypeFace from the dictionary.

I hope that makes sense, and is helpful.  I can't quickly post a working implementation, because my implementation of this logic has to achieve a bunch of other things on the side, and is rather entangled with several thousand lines of code for doing other things.  But if I can help more, please let me know,
