### ISSUE TITLE
MoveTo then Close path commands ends path prematurely.

### ISSUE THREAD

**Issue by Batboa** [wieslawsoltes/Svg.Skia#135]
For an SVG like the following the path ends before all commands are parsed:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="90.772 70.3143 20.22 20.885" style="">
   <g>
      <path stroke-width="5" fill="#5A7750" d="M59.9 37.5zm42 45.9c-.2-.2-.5.1-.3.3l.1-.1v.1s.1 0 .1-.1c0 0 .1 0 .1-.2zm-.2.3c-.4.3.5.2 0 0z" />
   </g>
</svg>
```

I can see the behavior coded here: https://github.com/wieslawsoltes/Svg.Skia/blob/master/src/Svg.Model/SvgExtensions.Pathing.cs#L273.

All browsers I tried seem to render this fine, and nothing in the path spec makes this seem invalid.

**Comment by wieslawsoltes** [comment]
Fixed in: https://github.com/wieslawsoltes/Svg.Skia/commit/d76590e1d5e0e4ea038ec6de8417a96ce83adfce and https://github.com/wieslawsoltes/Svg.Skia/commit/79b3d4c1f6044eeb8f5715af77e0cb5f37032020
