### ISSUE TITLE
Cannot create an instance of 

### ISSUE THREAD

**Issue by danipen** [wieslawsoltes/Svg.Skia#141]
Hi @wieslawsoltes!

I tried to upgrade to `11.0.0-preview5` but every time I try to create a new `SvgImage` I get the following exception:

```
'The type initializer for 'Avalonia.Svg.Skia.SvgImage' threw an exception.'
MethodAccessException: Attempt by method 
'Avalonia.Svg.Skia.SvgImage..cctor()' to access method 
'Avalonia.AvaloniaProperty.Register<Avalonia.Svg.Skia.SvgImage,Avalonia.Svg.Skia.SvgSource>(System.String, Avalonia.Svg.Skia.SvgSource, Boolean, Avalonia.Data.BindingMode, System.Func`2<Avalonia.Svg.Skia.SvgSource,Boolean>, System.Func`3<Avalonia.AvaloniaObject,Avalonia.Svg.Skia.SvgSource,Avalonia.Svg.Skia.SvgSource>, System.Action`2<Avalonia.AvaloniaObject,Boolean>)' failed.
```

Any idea about what's going on?

**Comment by wieslawsoltes** [comment]
Wow no idea, did you try running sample app? Are you sure there aren't any old Avalonia versions or Svg.Skia versions referenced?

**Comment by wieslawsoltes** [comment]
By any coincidence are you referencing both Avalonia.Svg and Avalonia.Svg.Skia in same project?

**Comment by wieslawsoltes** [comment]
I can't repro:
![image](https://user-images.githubusercontent.com/2297442/220904521-e7f872d2-1c52-497e-ab95-99f8c92ac7d6.png)

**Comment by danipen** [comment]
> By any coincidence are you referencing both Avalonia.Svg and Avalonia.Svg.Skia in same project?

No, but I'm using:   
```
<AvaloniaVersion>11.0.999-cibuild0030125-beta</AvaloniaVersion>
<SvgSkiaVersion>11.0.0-preview5</SvgSkiaVersion>
```

**Comment by danipen** [comment]
> Yeah probably some API breaking change in nightly that explains it.

That makes sense. Are you planning to upgrade to the latest changes?

**Comment by wieslawsoltes** [comment]
I will push update, but you need to use nightly feed https://pkgs.dev.azure.com/wieslawsoltes/GitHub/_packaging/Nightly/nuget/v3/index.json

**Comment by wieslawsoltes** [comment]
> I will push update, but you need to use nightly feed [pkgs.dev.azure.com/wieslawsoltes/GitHub/_packaging/Nightly/nuget/v3/index.json](https://pkgs.dev.azure.com/wieslawsoltes/GitHub/_packaging/Nightly/nuget/v3/index.json)

https://dev.azure.com/wieslawsoltes/GitHub/_artifacts/feed/Nightly

https://dev.azure.com/wieslawsoltes/GitHub/_build/results?buildId=9929&view=results

https://dev.azure.com/wieslawsoltes/GitHub/_release?_a=releases&view=all&definitionId=29

**Comment by wieslawsoltes** [comment]
@danipen 11.0.999-build20230223-03

**Comment by danipen** [comment]
Thanks! I'll try this afternoon!

**Comment by danipen** [comment]
Yes! that CI build is working as expected. Thanks a lot!

**Comment by danipen** [comment]
@wieslawsoltes I'm trying the latest Avalonia master changes, and I get the same error again. Could you please generate another CI build when you have some time so I can try those changes again? Thank you very much in advance!

**Comment by wieslawsoltes** [comment]
> @wieslawsoltes I'm trying the latest Avalonia master changes, and I get the same error again. Could you please generate another CI build when you have some time so I can try those changes again? Thank you very much in advance!

updated

**Comment by danipen** [comment]
where can I find the new CI build? (or is being built now)?

**Comment by wieslawsoltes** [comment]
> where can I find the new CI build? (or is being built now)?

https://dev.azure.com/wieslawsoltes/GitHub/_artifacts/feed/Nightly

https://pkgs.dev.azure.com/wieslawsoltes/GitHub/_packaging/Nightly/nuget/v3/index.json
