### ISSUE TITLE
Support for Avalonia v10.1.19

### ISSUE THREAD

**Issue by pavelovcharov** [wieslawsoltes/Svg.Skia#152]
Hello,

Will there be an update for Avalonia v10.1.19?

**Comment by wieslawsoltes** [comment]
The support is already there. Did you run into any issues?

**Comment by pavelovcharov** [comment]
Yes, there were some issues with the new avalonia version, but I was managed to fix them. Sorry for bothering you:)

**Comment by wieslawsoltes** [comment]
The 0.10.18 release is compatible with new 0.10.19 as 0.10.x maintains backward compatibility.
