### ISSUE TITLE
Fizzler depenency not MIT

### ISSUE THREAD

**Issue by JensNordenbro** [wieslawsoltes/Svg.Skia#162]
I have two questions on dependencies I hope you can briefly weigh in on :)  

Fizzler is a dependency of this package/repo that uses LGPL. 

https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License#Differences_from_the_GPL seems to say it is possible to link the dll:s included with a commercial application which is not without consequences with GPL however I am not sure what LGPL will demand of a commercial application. 

1. Do you have any policy on what dependencies you take on in the project? 
2. Are there any plans to change the dependencies of this project in a certain direction going forward?

**Comment by wieslawsoltes** [comment]
No policy, it's dependency from [Svg ](https://github.com/svg-net/SVG) project. See https://github.com/svg-net/SVG/issues/563

There was some idea to use AngleSharp or other library, but nobody did the work yet. I have no plans to do it.

**Comment by JensNordenbro** [comment]
al right, thanks for super swift reponse!
