### ISSUE TITLE
Publish a new version of Svg.Skia.Converter

### ISSUE THREAD

**Issue by ForNeVeR** [wieslawsoltes/Svg.Skia#180]
The last Svg.Skia.Converter version I see on nuget.org is pretty old, it's 0.4.1: https://www.nuget.org/packages/svg.skia.converter

Could you please update it to the latest version, so #164 gets resolved?

**Comment by wieslawsoltes** [comment]
Published https://www.nuget.org/packages/Svg.Skia.Converter/1.0.0.2

**Comment by ForNeVeR** [comment]
Thank you so much!
