### ISSUE TITLE
Svg.Skia NuGet with signed assemblies

### ISSUE THREAD

**Issue by punker76** [wieslawsoltes/Svg.Skia#19]
Is it possible that you can create a NuGet with signed assemblies?

This makes it possible to use your awesome lib also in such application scenarios.

like this

```
    <!-- Sign assembly -->
    <PropertyGroup>
        <SignAssembly>True</SignAssembly>
        <AssemblyOriginatorKeyFile>$(MSBuildProjectDirectory)\..\svg.skia.public.snk</AssemblyOriginatorKeyFile>
        <DelaySign>false</DelaySign>
        <PublicSign Condition=" '$(OS)' != 'Windows_NT' ">true</PublicSign>
    </PropertyGroup>
```

**Comment by wieslawsoltes** [comment]
I do not have signing certificates and for example https://www.digicert.com/code-signing/ is `$474/year`. So doing this for open-source project seems bit expensive.

**Comment by wieslawsoltes** [comment]
@punker76 Release https://www.nuget.org/packages/Svg.Skia/0.1.7

**Comment by punker76** [comment]
@wieslawsoltes Works perfectly, Thx
