### ISSUE TITLE
[Xamarin.Forms] Svg.Skia doesn't want to parse and display properly SVG

### ISSUE THREAD

**Issue by SeRgI1982** [wieslawsoltes/Svg.Skia#21]
I tried to use Svg.Skia exactly in the same way like in sample but no matter which .svg file I used, there is an output message during loading .svg file

> monotouch Error: 0 : Exception has been thrown by the target of an invocation.
monotouch Error: 0 : The CreateDocument method can only be used to parse root <svg> elements.
monotouch Error: 0 : The CreateDocument method can only be used to parse root <svg> elements.
monotouch Error: 0 : The CreateDocument method can only be used to parse root <svg> elements.
monotouch Error: 0 : The CreateDocument method can only be used to parse root <svg> elements.
monotouch Error: 0 : Stack empty.

Sample solution, below (tested on iOS, Android, macOS).
Embedded resource download.svg is a file taken from (https://github.com/wieslawsoltes/SVG/blob/d7a767942de86a0263941dd3e7cd4f939709f036/Tests/W3CTestSuite/svg/__Telefunken_FuBK_test_pattern.svg) which is used also in your official sample.

[SvgTest.zip](https://github.com/wieslawsoltes/Svg.Skia/files/4475799/SvgTest.zip)

**Comment by wieslawsoltes** [comment]
Can you try using normal file (not an embedded resource)?

**Comment by SeRgI1982** [comment]
In my production case, I download a whole data from my server, so my SVG is in string property of my Model. I will try to download it, save as file and load using path.

**Comment by SeRgI1982** [comment]
Ok, I have changed this sample project and currently, embedded resources are saved to device.
SKPicture is loaded via fila path and I would say that it is even worst:
- the same exception +

> System.NullReferenceException: Object reference not set to an instance of an object.
>   at Svg.SvgDocument.Open[T] (System.String path, System.Collections.Generic.Dictionary`2[TKey,TValue] entities) [0x00035] in D:\a\1\s\externals\SVG\Source\SvgDocument.cs:304 
>   at Svg.Skia.SKSvg.OpenSvg (System.String path) [0x00000] in D:\a\1\s\src\Svg.Skia\SKSvg.cs:127 
>   at Svg.Skia.SKSvg.Open (System.String path) [0x00006] in D:\a\1\s\src\Svg.Skia\SKSvg.cs:156 
>   at Svg.Skia.SKSvg.Load (System.String path) [0x00006] in D:\a\1\s\src\Svg.Skia\SKSvg.cs:181 
>   at SvgTest.MainPage.LoadImage (SvgTest.Item item) [0x0001e] in /Users/DevGroup/Projects/SvgTest/SvgTest/MainPage.xaml.cs:143 

- sometimes a Native exception appears

Tested on iOS/Android (simulator and real device)

Additionally, I have tested function SKSvg.FromSvg(string svgContent) but I have got the same issues. 
It looks like the problem lives in your one dependency library - Svg

Are you able to help with this ?

[SvgTest.zip](https://github.com/wieslawsoltes/Svg.Skia/files/4479712/SvgTest.zip)

**Comment by wieslawsoltes** [comment]
@SeRgI1982 I have problem on my machine to run Xamarin.Forms android to debug the issues specific to android. I can not test on iOS at all.

Can you try stepping through the Svg.Skia code and find where the exception is originating?

**Comment by SeRgI1982** [comment]
The same achieved on your sample

> {System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'Svg.SvgElement' threw an exception. ---> System.PlatformNotSupportedException: Operation is not supported on this platform.
>   at System.Drawing.Text.FontCollection..ctor () [0x00006] in <b4b162cd0c06466f81a75f1163524e4c>:0 
>   at System.Drawing.Text.PrivateFontCollection..ctor () [0x00000] in <b4b162cd0c06466f81a75f1163524e4c>:0 
>   at Svg.SvgElement..cctor () [0x0000a] in /Users/DevGroup/Svg.Skia/externals/SVG/Source/SvgElementStyle.cs:473 
>    --- End of inner exception stack trace ---
>   at Svg.SvgFragment..ctor () [0x00010] in /Users/DevGroup/Svg.Skia/externals/SVG/Source/Document Structure/SvgFragment.cs:15 
>   at Svg.SvgDocument..ctor () [0x00007] in /Users/DevGroup/Svg.Skia/externals/SVG/Source/SvgDocument.cs:94 
>   at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
>   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
>    --- End of inner exception stack trace ---
>   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00018] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:944 
>   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/ReferenceSources/RuntimeType.cs:185 
>   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/ReferenceSources/RuntimeType.cs:155 
>   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/rttype.cs:5770 
>   at System.Activator.CreateInstance[T] () [0x00029] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/activator.cs:236 
>   at Svg.SvgElementFactory.CreateElement[T] (System.Xml.XmlReader reader, System.Boolean fragmentIsDocument, Svg.SvgDocument document) [0x0003e] in /Users/DevGroup/Svg.Skia/externals/SVG/Source/SvgElementFactory.cs:93 
>   at Svg.SvgElementFactory.CreateDocument[T] (System.Xml.XmlReader reader) [0x00035] in /Users/DevGroup/Svg.Skia/externals/SVG/Source/SvgElementFactory.cs:62 
>   at Svg.SvgDocument.Open[T] (System.Xml.XmlReader reader) [0x000a0] in /Users/DevGroup/Svg.Skia/externals/SVG/Source/SvgDocument.cs:395 }

PrivateFontCollection constructor calls 

`GDIPlus.CheckStatus (GDIPlus.GdipNewPrivateFontCollection (out _nativeFontCollection));`

I guess that something is wrong here.

**Comment by wieslawsoltes** [comment]
@SeRgI1982 Seems like issue with some missing functionality from System.Drawing on Android/iOS. trying to fix this https://github.com/vvvv/SVG/pull/711 

I will publish patched version of SVG with Svg.Skia that includes this fix in version 0.1.8.
