### ISSUE TITLE
0 packages on https://www.myget.org/F/svgskia-nightly/api/v2

### ISSUE THREAD

**Issue by ezruneko** [wieslawsoltes/Svg.Skia#22]
No packages on https://www.myget.org/F/svgskia-nightly/api/v2

Thank you

**Comment by wieslawsoltes** [comment]
Please check the `preview` button if using `Visual Studio`.

Check the gallery to see available packages: https://www.myget.org/gallery/svgskia-nightly

Add `-Pre` option to install command:
```
Install-Package Svg.Skia -Pre -Source https://www.myget.org/F/svgskia-nightly/api/v3/index.json
```

**Comment by wieslawsoltes** [comment]
@ezruneko 
![devenv_2020-04-15_18-01-05](https://user-images.githubusercontent.com/2297442/79359634-22b44f80-7f43-11ea-85d4-417c3d98db1f.png)
