### ISSUE TITLE
DrawingContext.DrawImage() method not draws an SvgImage in some cases

### ISSUE THREAD

**Issue by VladimirDrobyshev** [wieslawsoltes/Svg.Skia#227]
If target rectangle has non zero location and its size is not equal to SvgImage size the SvgImage is not dfrawing correctly.

SvgImage with size (20, 20)
1) not drawns:
```
        context.DrawImage(svgImage, new Rect(100, 100, 10, 10));
```
2) drawns correctly:
```
        context.DrawImage(svgImage, new Rect(0, 0, 10, 10));
```
3) drawns correctly:
```
        context.DrawImage(svgImage, new Rect(100, 100, 20, 20));
```

**Comment by wieslawsoltes** [comment]
Fixed by https://github.com/wieslawsoltes/Svg.Skia/pull/228
