### ISSUE TITLE
Avalonia control misrenders nested groups with non-trivial transforms

### ISSUE THREAD

**Issue by mishun** [wieslawsoltes/Svg.Skia#234]
Hi!

Following SVG contains red circle and blue circle almost exactly half the size:
```svg
<svg width="200" height="200">
   <circle cx="100" cy="100" r="100" fill="red" />
   <g transform="scale(0.5)">
     <g transform="scale(0.999)">
       <circle cx="100" cy="100" r="100" fill="blue" />
     </g>
   </g>
</svg>
```

When pasted into `AvaloniaSvgSample` actual result is blue circle approximately quarter the size:
![avalonia-svg](https://github.com/wieslawsoltes/Svg.Skia/assets/1227703/eb65c7e7-baf0-4a43-8a44-44e9bb747b6b)

I played around with it a bit and it seems that external group's transform is applied twice when internal group's transform is non-trivial. Tested against latest master branch.

**Comment by mishun** [comment]
Okay, I think I'm starting to understand what's going on here. Each group gets it's total transformation matrix (relative to root element of SVG, I guess?) computed here:
https://github.com/wieslawsoltes/Svg.Skia/blob/f987aafd8f78d5558e089cb9aea5552b6abd47ff/src/Svg.Model/Drawables/DrawableBase.cs#L115-L120
And that `SetMatrix` eventually becomes `PushTransform` here:
https://github.com/wieslawsoltes/Svg.Skia/blob/f987aafd8f78d5558e089cb9aea5552b6abd47ff/src/Avalonia.Svg/AvaloniaPicture.cs#L270-L276
So of course top level transform gets accounted twice. And since `DrawingContext` can only do `PushTransform` and there's also probably additional render transform on stack inherited from top level logic, I don't see any way to fix it without dealing with relative transformations only.

**Comment by wieslawsoltes** [comment]
I think this is fixed:

![image](https://github.com/user-attachments/assets/67b57fe1-80ce-4190-9921-d4f71603d8e3)
