### ISSUE TITLE
wasm-tools-net6 requirement for Blazor publish?

### ISSUE THREAD

**Issue by benbaker76** [wieslawsoltes/Svg.Skia#239]
When publishing my Blazor Wasm (.NET 8.0) app it forced me to install `wasm-tools-net6` or it would give me an error `To build this project, the following workloads must be installed: wasm-tools-net6. To install these workloads, run the following command: dotnet workload restore`.

Is this issue caused by [install-dotnet-workloads.ps1](https://github.com/mono/SkiaSharp/blob/main/scripts%2Finstall-dotnet-workloads.ps1#L30)?

Also I need to include the`SkiaSharp.Views.Blazor` dependency or I get `System.DllNotFoundException: libSkiaSharp`. Why can't I just use `SkiaSharp.NativeAssets.WebAssembly`?

**Comment by wieslawsoltes** [comment]
Svg.Skia does not requires this workloads
