### ISSUE TITLE
Issue with changing stroke color

### ISSUE THREAD

**Issue by Ubus99** [wieslawsoltes/Svg.Skia#243]
Hi, I am new to svg.skia + AvaloniaUI and am trying to change an SVG's color, but nothing happens.
I am using the ![circle-plus](https://github.com/user-attachments/assets/d6044d14-ba28-43c3-b58a-5aad0c3fd5d4) from lucide loaded using:
```
<Svg Path="/Assets/icons/circle-plus.svg" Css=" { stroke: #FFFFFF; }" />
```
But it doesn't turn white. I am unsure if this is a bug or if I am doing something wrong.
I have also tried it without the brackets or with `.Black` (I am not sure what this selector targets in your example)

**Comment by wieslawsoltes** [comment]
Css="stroke: white;"
