### ISSUE TITLE
Missing Path

### ISSUE THREAD

**Issue by CodeDevAM** [wieslawsoltes/Svg.Skia#247]
In my App I use the [tabler copy](https://tabler.io/icons/icon/copy) as an icon. This SVG has basically 2 paths but unfortunately only one of these two is rendered.

Expectation:
![grafik](https://github.com/user-attachments/assets/c812ad2c-fa18-48c9-8f3e-d66bfe97d003)

Actual:
![grafik](https://github.com/user-attachments/assets/a8783d79-2ac7-4626-abd8-9a679df9dd32)

Info: I am using Avalonia 11.2.0-rc2 on Windows 11 with Avalonia.Svg 11.1.0.1

**Comment by wieslawsoltes** [comment]
Fixed in https://github.com/wieslawsoltes/Svg.Skia/commit/83c684acb4b0c542d295154922aca39660e4d977
