### ISSUE TITLE
UWP app rejected by Certification Testing

### ISSUE THREAD

**Issue by jrc14** [wieslawsoltes/Svg.Skia#25]
Hi - I've built a UWP app using Svg.Skia, but it is failing Windows certification testing with this message:

`API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libSkiaSharp.dll calls this API.`
`API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libGLESv2.dll calls this API.`
`API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. Microsoft.Graphics.Canvas.dll calls this API.`
`API __CxxFrameHandler4 in vcruntime140_1_app.dll is not supported for this application type. libHarfBuzzSharp.dll calls this API.`

Any ideas?

**Comment by jrc14** [comment]
Hi - a quick update - I think this might be a fault with the Windows App Certification Kit.  I'm following up on that, so perhaps you should avoid taking any action for the time being.  If I confirm it's a fault with the certification kit, I'll close the issye

**Comment by wieslawsoltes** [comment]
Seems like bug in store and it's pretty common https://github.com/microsoft/microsoft-ui-xaml/issues/1446

**Comment by wieslawsoltes** [comment]
And Microsoft.Graphics.Canvas.dll is part of Win2D, Microsoft own project.
