### ISSUE TITLE
Comparison with SkiaSharp.Extended.Svg

### ISSUE THREAD

**Issue by jgimness** [wieslawsoltes/Svg.Skia#3]
Could you provide some info about the library objectives and how it compares to the SkiaSharp.Extended.Svg library? ( https://github.com/mono/SkiaSharp.Extended/blob/master/SkiaSharp.Extended.Svg/README.md )

I think that would be helpful for people browsing (found your library via a google search)

Thanks!

**Comment by wieslawsoltes** [comment]
@jgimness 

The `Svg.Skia` is using internally [SVG](https://github.com/vvvv/SVG) library from [NuGet](https://www.nuget.org/packages/Svg) to load `Svg` object model. The original `Svg` library provides only `System.Drawing` rendering backend. The `Svg.Skia` library is providing rendering backend implementation using `SkiaSharp` that aims to be at least on par or more complete then original `System.Drawing` implementation and also more performant. The `Svg.Skia` can be also be used in same way as the [SkiaSharp.Extended.Svg](https://github.com/mono/SkiaSharp.Extended/tree/master/SkiaSharp.Extended.Svg)  (load `svg` files as `SKPicture`). The `Svg` library has more complete implementation of `Svg` document model then [SkiaSharp.Extended.Svg](https://github.com/mono/SkiaSharp.Extended/tree/master/SkiaSharp.Extended.Svg) and the `Svg.Skia` renderer will provide more complete rendering subsystem implementation.

**Comment by wieslawsoltes** [comment]
@jgimness I have add my above answer to README https://github.com/wieslawsoltes/Svg.Skia/blob/master/README.md#about

Please let me know if About clarification is clear or can be improved.
