### ISSUE TITLE
Svg.Skia does not work with UWP, in release builds

### ISSUE THREAD

**Issue by jrc14** [wieslawsoltes/Svg.Skia#31]
Not sure why you've closed the issue 'XamarinFormsDemo.UWP does not work in Release (Solution Configuration)' without a resolution.  It's blocking for me.

It means that your library works fine with Debug builds, but when you build a UWP project for Release (which means the Native .Net toolchain is used), you get code that always throws a Type Initialization Exception, from this code:
```
using (SKSvg svg = new SKSvg())
{
  SKPicture pic = svg.FromSvg(svgText);
}
```
It's happening because some code in the SVG library is calling an interop that is illegal in UWP.  The interop is called from GetSystemDpi() in SvgDocument.cs.  A potential work-around would be to edit your implementation code in svg.custom, so as to avoid calling the illegal interop.

**Comment by inforithmics** [comment]
When one of my pull requests is merged for https://github.com/vvvv/SVG/issues/736 then I can make a pull request to this project (Adding UWP Target) and it should work on UWP

**Comment by wieslawsoltes** [comment]
Ported changes from https://github.com/vvvv/SVG/pull/739 to Svg.Custom
