### ISSUE TITLE
Text of custom fonts not rendering

### ISSUE THREAD

**Issue by DrHeimdall** [wieslawsoltes/Svg.Skia#39]
I'm making a gui program in avalonia with a custom ui and planned on using dynamically rendered svgs for the ui. I begun with creating the splash screen but I can't seem to render the text using your library. I am using the skiasharp bundled with Avalonia (so it doesn't mess up the natives) and I made the splash screen (and will make all svg files) using Inkscape.

This is what I could get your library to do: [https://imgur.com/a/JRimmyn](https://imgur.com/a/JRimmyn)
This is what Inkscape renders: [https://imgur.com/a/Vy7SRPq](https://imgur.com/a/Vy7SRPq)

I have attempted to give Svg.Skia.SKSvgSettings.s_typefa... and also Svg.SvgFontManager (I've tried individually and both at the same time) both all of the ttf at the same time and also just the ttf I used in the svg renamed to the exact name which is referenced in the svg but it never renders the text. For reference, I also have all of the Quantico (the font in question) fonts installed on my system and have tried sans-serif also with no avail.

My entire repo (it's very small rn, I've only just started making it) is [here](https://github.com/DrHeimdall/texture-jinn). I'm running pop-os (basically ubuntu) 20.04 LTS on x86 64bit. I have dotnet core 3.1.302 installed and the repo target framework is `netcoreapp3.1`. I'm using Svg.Skia 0.3.0 and take my skiasharp version (I guess) from avalonia 0.10.0-preview1. Program.cs is [currently](https://github.com/DrHeimdall/texture-jinn/tree/660cc36c3df8614f0f0dd42933da3ca6c6e8f0c5) setup to produce test.png at a vertical resolution of 720px from `Assets/Images/Vector Images/SplashBase.svg` using fonts in the directory `Assets/Fonts/Quantico`.

I'm still confused as to weather this is a bug, something to do with how Inkscape compiles svgs or something else entirely. I hope that you can find out what's going on!

**Comment by wieslawsoltes** [comment]
The svg is using flowRoot element which is unsupported.

**Comment by wieslawsoltes** [comment]
https://graphicdesign.stackexchange.com/questions/21662/how-does-inkscape-decide-whether-to-use-flowroot-or-text

**Comment by wieslawsoltes** [comment]
https://www.w3.org/TR/2004/WD-SVG12-20041027/flow.html

It is Svg 1.2, the Svg.Skia supports Svg 1.1, please note that text rendering is very basic and no plans for near feature on extending that part as it is pretty huge undertaking.

**Comment by DrHeimdall** [comment]
Ah, amazing, thank you! Thanks so much for the stackoverflow answer as well, really helpful and everything should work now!
