### ISSUE TITLE
Remove SkiaSharp.NativeAssets.Linux

### ISSUE THREAD

**Issue by charlesroddie** [wieslawsoltes/Svg.Skia#4]
Installing Svg.Skia into a netstandard project brings in SkiaSharp.NativeAssets.Linux.
https://github.com/wieslawsoltes/Svg.Skia/search?q=linux&unscoped_q=linux
Since this project shouldn't have a linux dependency, can this be removed?

**Comment by wieslawsoltes** [comment]
@charlesroddie Removed this dependency from Svg.Skia. Will be included in the next preview release.
