### ISSUE TITLE
[ UWP ] System.NullReferenceException: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by FoggyFinder** [wieslawsoltes/Svg.Skia#40]
Happens only in Release mode. It looks like a bug in the .net native at first glance.

MCVE
```xaml
<skia:SKCanvasView
    HorizontalOptions="FillAndExpand"
    PaintSurface="OnPaintSurface"
    VerticalOptions="FillAndExpand" />
```

```cs
public partial class MainPage : ContentPage
{
    private readonly SKPicture picture;
    private readonly string svg = "<svg xmlns=\"http://www.w3.org/2000/svg\"><g id = \"moti\" fill=\"white\" stroke=\"green\" stroke-width=\"5\"><circle cx = \"40\" cy=\"40\" r=\"25\" /><circle cx = \"60\" cy=\"60\" r=\"25\" /></g></svg>";
    public MainPage()
    {
        InitializeComponent();
        var ba = Encoding.UTF8.GetBytes(svg);
        var sr = new MemoryStream(ba);
        var sksvg = new SKSvg();
        picture = sksvg.Load(sr);
    }

    private void OnPaintSurface(object sender, SKPaintSurfaceEventArgs e)
    {
        var canvas = e.Surface.Canvas;
        var scale = (float)(e.Info.Width / skiaView.Width);
        canvas.Scale(scale);
        canvas.Clear(SKColors.White);

        canvas.DrawPicture(picture);
    }
}
```

caused by 

```cs
descriptor.Converter.ConvertFrom(document, CultureInfo.InvariantCulture, attributeValue)
```
[here](
https://github.com/vvvv/SVG/blob/7f72d36d70309293adebb66e72a71ced54ce924b/Source/SvgElementFactory.cs#L269)

It doesn't like `id = \"moti\"` for some reason.

**Comment by wieslawsoltes** [comment]
Maybe some metadata is missing in release version, could you try add Svg.Custom to rd.xml file?

**Comment by FoggyFinder** [comment]
```xml
<Assembly Name="Svg.Custom" Dynamic="Required All" />
```

^ same result

**Comment by wieslawsoltes** [comment]
Do you have stack trace and also can you debug and tell me which variable is null?

**Comment by FoggyFinder** [comment]
Resolved with

```xml
<Assembly Name="System.ComponentModel.TypeConverter" Dynamic="Required All" />
```

Would be better to include something more specific than that though

**Comment by wieslawsoltes** [comment]
> Resolved with
> 
> ```
> <Assembly Name="System.ComponentModel.TypeConverter" Dynamic="Required All" />
> ```
> 
> Would be better to include something more specific than that though

Are there more verbose release mode diagnostics. When doing rd.xml files for CoreRT this was helpful to find more granular types in rd.xml definitions.

**Comment by FoggyFinder** [comment]
Exactly. For CoreRt I included the line below to a proj file:

```
<IlcArg Include="--verbose" />
```

and it indeed helped me a lot to understand issues with my app. Dunno how to use it with .net native if it possible at all. Probably I should just experiment with it a bit :-)

I haven't expected metadata issues because usually there is "Missing...Exception" which is easy to understand.

**Comment by charlesroddie** [comment]
Moved to svg-net since the underlying problem is there:
https://github.com/svg-net/SVG/issues/1061
