### ISSUE TITLE
SVG file that is not correctly handled 

### ISSUE THREAD

**Issue by srqdev** [wieslawsoltes/Svg.Skia#41]
I found a file that when I simply load and then save to a PNG, all the PNG contains is a transparent PNG. No rendering of the image has occurred.  The text of the SVG is below and is a circular cutoff the Puerto Rico flag. So very straightforward.

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg
   xmlns:dc="http://purl.org/dc/elements/1.1/"
   xmlns:cc="http://creativecommons.org/ns#"
   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"
   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
   height="620"
   width="620"
   id="svg10"
   version="1.1"
   fill="#ffffff"
   sodipodi:docname="PuertoRicoFlag.svg"
   inkscape:version="1.0 (4035a4fb49, 2020-05-01)">
  <metadata
     id="metadata16">
    <rdf:RDF>
      <cc:Work
         rdf:about="">
        <dc:format>image/svg+xml</dc:format>
        <dc:type
           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />
        <dc:title></dc:title>
      </cc:Work>
    </rdf:RDF>
  </metadata>
  <defs
     id="defs14">
    <clipPath
       clipPathUnits="userSpaceOnUse"
       id="clipPath21">
      <g
         id="g25"
         transform="matrix(0.99337116,0,0,0.99337116,-0.15530322,2.3329428)">
        <circle
           style="fill:#143d75;stroke-width:6.61279;stroke-linecap:round;stroke-linejoin:round;stroke-opacity:0.4"
           id="circle23"
           cx="382.69211"
           cy="299.65341"
           r="302.00192" />
      </g>
    </clipPath>
    <clipPath
       clipPathUnits="userSpaceOnUse"
       id="clipPath27">
      <g
         id="g31"
         transform="matrix(0.99337116,0,0,0.99337116,-0.15530322,2.3329428)">
        <circle
           style="fill:#143d75;stroke-width:6.61279;stroke-linecap:round;stroke-linejoin:round;stroke-opacity:0.4"
           id="circle29"
           cx="382.69211"
           cy="299.65341"
           r="302.00192" />
      </g>
    </clipPath>
    <clipPath
       clipPathUnits="userSpaceOnUse"
       id="clipPath33">
      <g
         id="g37"
         transform="matrix(0.99337116,0,0,0.99337116,-0.15530322,2.3329428)">
        <circle
           style="fill:#143d75;stroke-width:6.61279;stroke-linecap:round;stroke-linejoin:round;stroke-opacity:0.4"
           id="circle35"
           cx="382.69211"
           cy="299.65341"
           r="302.00192" />
      </g>
    </clipPath>
    <clipPath
       clipPathUnits="userSpaceOnUse"
       id="clipPath39">
      <g
         id="g43"
         transform="matrix(0.99337116,0,0,0.99337116,-0.15530322,2.3329428)">
        <circle
           style="fill:#143d75;stroke-width:6.61279;stroke-linecap:round;stroke-linejoin:round;stroke-opacity:0.4"
           id="circle41"
           cx="382.69211"
           cy="299.65341"
           r="302.00192" />
      </g>
    </clipPath>
  </defs>
  <sodipodi:namedview
     inkscape:current-layer="svg10"
     inkscape:window-maximized="1"
     inkscape:window-y="-8"
     inkscape:window-x="1912"
     inkscape:cy="387.52919"
     inkscape:cx="424.35034"
     inkscape:zoom="0.71913184"
     showgrid="false"
     id="namedview12"
     inkscape:window-height="1057"
     inkscape:window-width="1920"
     inkscape:pageshadow="2"
     inkscape:pageopacity="0"
     guidetolerance="10"
     gridtolerance="10"
     objecttolerance="10"
     borderopacity="1"
     bordercolor="#666666"
     pagecolor="#ffffff"
     inkscape:document-rotation="0"
     showguides="true"
     inkscape:guide-bbox="true"
     fit-margin-top="10"
     lock-margins="true"
     fit-margin-left="10"
     fit-margin-right="10"
     fit-margin-bottom="10" />
  <path
     style="stroke-width:1.05409;fill:#ffffff"
     id="path2"
     d="M 0,0 H 1000 V 600 H 0"
     clip-path="url(#clipPath39)"
     transform="translate(-70,10)" />
  <path
     id="path4"
     d="m 0,60 h 1000 m 0,240 H 0 m 0,240 h 1000"
     stroke-width="126.491"
     stroke="#ee0000"
     clip-path="url(#clipPath33)"
     transform="translate(-70,10)" />
  <path
     style="stroke-width:1.05409"
     id="path6"
     d="M 0,0 V 600 L 577.77778,300"
     fill="#0050f0"
     clip-path="url(#clipPath27)"
     transform="translate(-70,10)" />
  <path
     style="stroke-width:1.05409"
     id="path8"
     d="M 126.66667,382 192.22222,199 257.77778,382 85.555556,269 H 298.88889"
     clip-path="url(#clipPath21)"
     transform="translate(-70,10)" />
</svg>
`

**Comment by wieslawsoltes** [comment]
Text support is very basic to bugs related to text are expected.

**Comment by wieslawsoltes** [comment]
When I load provided SVG into chrome (and Edge) browser the result is the same - transparent image. So issue is with Svg itself.

**Comment by wieslawsoltes** [comment]
![2020-12-28_12-58-21](https://user-images.githubusercontent.com/2297442/103212904-6baf0700-490c-11eb-8b77-08cdd062b56b.png)
