### ISSUE TITLE
SVG to PNG/PDF text position incorrect

### ISSUE THREAD

**Issue by Kim-SSi** [wieslawsoltes/Svg.Skia#42]
Converting the attached svg to png using Svg.Skia results in the incorrect position of the text.
SvgNet renders the text position correctly in the png, but has other issues.
I have included the png/pdf output of the svg when open from Inkscape and Chrome which match SvgNet.

[Reproducer1-Chrome.pdf](https://github.com/wieslawsoltes/Svg.Skia/files/4992082/Reproducer1-Chrome.pdf)
[Reproducer1-Inkscape.pdf](https://github.com/wieslawsoltes/Svg.Skia/files/4992083/Reproducer1-Inkscape.pdf)
[Reproducer1SVG.zip](https://github.com/wieslawsoltes/Svg.Skia/files/4992085/Reproducer1SVG.zip)
[SvgReproducer-proj.zip](https://github.com/wieslawsoltes/Svg.Skia/files/4992086/SvgReproducer-proj.zip)

Numbers position wrong on the left:
[Reproducer1-Skia Svg](https://user-images.githubusercontent.com/28267812/88748770-f9dc6100-d1a5-11ea-9355-f4eba4789762.png)

Correct output:
[Reproducer1-Inkscape](https://user-images.githubusercontent.com/28267812/88748767-f943ca80-d1a5-11ea-805c-0994610d031b.png)

Text position correct via SvgNet
[Reproducer1-SvgNet](https://user-images.githubusercontent.com/28267812/88748773-fa74f780-d1a5-11ea-9f03-29b5483b9645.png)

**Comment by wieslawsoltes** [comment]
Text support is very basic so issues are expected.
