### ISSUE TITLE
The result is blurry

### ISSUE THREAD

**Issue by edward-a** [wieslawsoltes/Svg.Skia#43]
I am getting blurry results when rendering an SVG in UWP app. Below is the code I use to draw SVG in SKXamlCanvas.PaintSurface event handler.

			var canvas = e.Surface.Canvas;
			var display = DisplayInformation.GetForCurrentView();
			var scale = display.LogicalDpi / 96.0f;
			var scaledSize = new SKSize(e.Info.Width / scale, e.Info.Height / scale);
			canvas.Scale(scale);
			canvas.Clear(SKColors.Transparent);
			if (svg != null) {
				float scaleX = scaledSize.Width / svg.Picture.CullRect.Width;
				float scaleY = scaledSize.Height / svg.Picture.CullRect.Height;
				var matrix = SKMatrix.MakeScale(scaleX, scaleY);
				canvas.DrawPicture(svg.Picture, ref matrix);
			}

**Comment by wieslawsoltes** [comment]
Is result blurry without scaling matrix?

**Comment by wieslawsoltes** [comment]
This is SkiaSharp / UWP issue, WPF and Avalonia render images correctly.
