### ISSUE TITLE
SVG line on axis not handling linearGradient with 0 offset correctly

### ISSUE THREAD

**Issue by dedmen** [wieslawsoltes/Svg.Skia#46]
Full example svg file (named txt so I can upload it here)
[Chernarus_Winter.txt](https://github.com/wieslawsoltes/Svg.Skia/files/5125863/Chernarus_Winter.txt)

Left Google Chrome
Center Mozilla Firefox
Right Svg.Skia rendered onto a canvas

![2020-08-25_21-24-56](https://user-images.githubusercontent.com/3768165/91218514-7452bf00-e719-11ea-80f4-5bd9f83557e3.png)

Minimal example
```
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500">
<defs>
<linearGradient id="colorGrid"><stop offset="0" stop-color="#707053" /></linearGradient>
</defs>

<g id="grid" stroke="url(#colorGrid)" fill="url(#colorGrid)">
<line x1="0.00" y1="0" x2="0.00" y2="15360.00"  stroke-width="4"/>
<text x="50.00" y="50.00">000</text>
<line x1="100.00" y1="0" x2="100.01" y2="15358.00"/>
<text x="150.00" y="50.00">001</text>
<line x1="200.00" y1="15360.00" x2="200.00" y2="0.00"/>
<text x="250.00" y="50.00">002</text>
<line x1="300.00" y1="15360.00" x2="300.00" y2="0.00"/>
<text x="350.00" y="50.00">003</text>
<line x1="400.00" y1="15360.00" x2="400.00" y2="0.00"/>
</g>

</svg>
```

Even setting stroke-width="20" makes them not render, same behavior in Chrome browser.

changing
`<line x1="100.00" y1="0" x2="100.00" y2="15358.00"/>`
to
`<line x1="100.00" y1="0" x2="100.01" y2="15358.00"/>`
will make it render in both Chrome and Svg.Skia

stop offset="0" is a "standard" way to hardcode colors as defs, and Firefox also handles it correctly. And I think old SkiaSharp.Svg handled it correctly, my grid lines stopped displaying when I switched over to Svg.Skia.

Atleast as long as https://developer.mozilla.org/en-US/docs/Web/SVG/Element/solidColor is not supported.

**Comment by wieslawsoltes** [comment]
Try adding `gradientUnits="userSpaceOnUse"` to linearGradient

**Comment by wieslawsoltes** [comment]
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/gradientUnits

gradientUnits default value objectBoundingBox is using the bounding box of the element so vertical line have 0 width and horizontal 0 height

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/Svg.Skia/blob/84fee4999877260f9d2513f4a065750274c0598c/src/Svg.Skia/Svg/SvgExtensions.cs#L991-L1002

So when bounding box has 0 height or width what we should do?

https://www.w3.org/TR/SVG11/pservers.html#LinearGradientElementGradientUnitsAttribute
https://www.w3.org/TR/SVG11/coords.html#ObjectBoundingBox
```
Keyword objectBoundingBox should not be used when the geometry of the applicable element has no width or no height, such as the case of a horizontal or vertical line, even when the line has actual thickness when viewed due to having a non-zero stroke width since stroke width is ignored for bounding box calculations. When the geometry of the applicable element has no width or height and objectBoundingBox is specified, then the given effect (e.g., a gradient or a filter) will be ignored.
```

**Comment by dedmen** [comment]
> Try adding gradientUnits="userSpaceOnUse" to linearGradient

yes that fixes it thanks.
I assume this can be closed then, didn't think to search for problems with the gradient itself.
