### ISSUE TITLE
Is the library compatible with Xamarin.Forms?

### ISSUE THREAD

**Issue by ChristopherStephan** [wieslawsoltes/Svg.Skia#47]
Hi,

is this library compatible with Xamarin.Forms? So far I could not make it work.

```
<ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Miele.Libraries.UiComponents.Sandbox.ImagesPage"
             xmlns:svg="clr-namespace:Svg.Skia.Avalonia;assembly=Svg.Skia.Avalonia">
    <ContentPage.Resources>
        <svg:SvgImage x:Key="__tiger" Source="/Assets/__tiger.svg"/>
    </ContentPage.Resources>
    <ContentPage.Content>
        <Image Name="svgResourceImage" Source="{DynamicResource __tiger}"/>
    </ContentPage.Content>
</ContentPage>
```

I get the error "Assembly 'Svg.Skia.Avalonia' was not found." for the svg namespace. I am using version 0.10.0-preview1 of AvaloniaUI. Also, the `Image.Name` property does not exist for Xamarin.Forms.Image.

Regards
Christopher

**Comment by FoggyFinder** [comment]
Wrong package. You should use `Svg.Skia` instead of `Svg.Skia.Avalonia` for XF.

**Comment by wieslawsoltes** [comment]
The library yes, but you have to use SkiaSharp views and render content yourself using loaded SKPicture by SKSvg.

**Comment by 15mgm15** [comment]
I've just found my answer, thanks @wieslawsoltes

**Comment by 15mgm15** [comment]
@FoggyFinder  Did you ended up implementing this library? By any chance, do you have a code snippet?

**Comment by FoggyFinder** [comment]
code snippet for what?

**Comment by 15mgm15** [comment]
@FoggyFinder Your implementation of this library using Xamarin.Forms

**Comment by FoggyFinder** [comment]
@15mgm15  this library is compatible with XF as is

**Comment by FoggyFinder** [comment]
Sample: https://github.com/FoggyFinder/XFMCVE1

**Comment by 15mgm15** [comment]
@FoggyFinder By any chance do you have a C# sample?

**Comment by FoggyFinder** [comment]
@15mgm15 not sure. But it should be pretty straightforward to translate from F#. If you have any particular Qs feel free to ask.
