### ISSUE TITLE
Fonts on Android

### ISSUE THREAD

**Issue by charlesroddie** [wieslawsoltes/Svg.Skia#48]
Wondering how to display SVGs with fonts on Android.

We tried using `font-family="Arial, sans-serif"`, and `font-family="Roboto"`, but none of these are getting picked up on Xamarin.Android.

Font specifications and fallbacks seem to work fine on UWP.

cc: @kevcrooks

**Comment by wieslawsoltes** [comment]
Do not have setup for testing on Android. You can debug typeface provider here:

https://github.com/wieslawsoltes/Svg.Skia/blob/15a6f5393a178ebf780024471c483bb13235cecc/src/Svg.Skia/SKSvgSettings.cs#L19

This is default font provider:

https://github.com/wieslawsoltes/Svg.Skia/blob/15a6f5393a178ebf780024471c483bb13235cecc/src/Svg.Skia/Typeface/FontManagerTypefacerovider.cs#L39

**Comment by kevcrooks** [comment]
We've just tested this with @charlesroddie again now on Android, and it seems to be working, so this issue can be closed
