### ISSUE TITLE
Svg.Custom not compatible with linking

### ISSUE THREAD

**Issue by charlesroddie** [wieslawsoltes/Svg.Skia#49]
Svg.Custom is referenced by Svg.Skia and is not compatible with linking.

Workaround: skip linking manually for Svg.Custom

Is there some reflection that is required in this framework that is giving a linker incompatibility?

Tested on Android.

Other platforms (UWP release mode, iOS) not tested but could have similar issues.

**Comment by charlesroddie** [comment]
I see this comes from a fork of https://github.com/vvvv/SVG so should I move this issue there?

**Comment by wieslawsoltes** [comment]
Probably reflection in Svg.Custom (it's not a fork, just custom csproj).

**Comment by wieslawsoltes** [comment]
@charlesroddie https://github.com/wieslawsoltes/Svg.Skia/issues/40#issuecomment-664998730

**Comment by wieslawsoltes** [comment]
This is linker issue, solved by custom rd.xml files.
