### ISSUE TITLE
Defining SVG color

### ISSUE THREAD

**Issue by stashymane** [wieslawsoltes/Svg.Skia#51]
With CSS it is possible to define the color of SVGs via the `fill` property - would be nice having that here as well.

**Comment by wieslawsoltes** [comment]
Do you have svg example with fill that is not working ?

**Comment by stashymane** [comment]
The issue is not that fill is not working - the issue is that it would be nice to have a way to customize SVG color inside XAML and not creating a duplicate svg file with only the fill color changed.

**Comment by wieslawsoltes** [comment]
That would be nice indeed, but the way Svg library works and Svg.Skia was built it's expensive operation as we have to parse css and rebuild entire picture.

**Comment by AlexSchuetz** [comment]
Would it be able to add some transformations like in Xamarin with [ffimageloading](https://github.com/luberda-molinet/FFImageLoading)? Like Rotation and Tint.

**Comment by wieslawsoltes** [comment]
I think for now it's beyond scope of this project.

**Comment by MihaMarkic** [comment]
> Would it be able to add some transformations like in Xamarin with [ffimageloading](https://github.com/luberda-molinet/FFImageLoading)? Like Rotation and Tint.

Tint would be awesome to have. Rotate can be at least done by host, though.
