### ISSUE TITLE
Use xml code instead of svg file?

### ISSUE THREAD

**Issue by nitanmarcel** [wieslawsoltes/Svg.Skia#54]
Is there a way to use the xml code instead of a svg file? I'm working on a live editing tool and it will be pretty handy for me to just use the xml text instead of the svg file since my project requires binding between css and xml to edit the svg,

Thanks!

**Comment by wieslawsoltes** [comment]
You can load from xml using stream.

**Comment by wieslawsoltes** [comment]
https://github.com/wieslawsoltes/Svg.Skia/blob/216a01367ddf4c88373943ae988c23f3a7805eac/src/Svg.Skia/SKSvg.cs#L195-L201
