### ISSUE TITLE
Fill setting is invalid

### ISSUE THREAD

**Issue by Zhangoo** [wieslawsoltes/Svg.Skia#56]
``` xml
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0" y="0" width="165" height="165">
    <g id="dot" x="0" y="0" width="0.5" height="0.5">
        <rect fill="red" width="120" height="120" />
        <circle fill="black" cx="50" cy="50" r="25" />
    </g>
</svg>
```

When drawing this svg, the color is all black.
fill="red" is invalid.
Can you please confirm. @wieslawsoltes 

Version 0.41

**Comment by wieslawsoltes** [comment]
The Svg renders just fine, don't see any issue here.

Svg.Skia (master branch)

![dotnet_2021-01-01_13-09-05](https://user-images.githubusercontent.com/2297442/103438347-ab3e6180-4c32-11eb-838e-b33688b69530.png)

Chrome

![chrome_2021-01-01_13-09-18](https://user-images.githubusercontent.com/2297442/103438350-b2fe0600-4c32-11eb-9458-fac79507e74a.png)

**Comment by wieslawsoltes** [comment]
Try using latest nightly build https://www.myget.org/F/svgskia-nightly/api/v2
