### ISSUE TITLE
em unit is not relative to the font size.

### ISSUE THREAD

**Issue by Batboa** [wieslawsoltes/Svg.Skia#57]
When converting unit defined in _em_ to a device value the font size is not taken into account. This deviates from the [SVG spec on coordinates ](https://www.w3.org/TR/SVG11/coords.html), specifically 7.10. If the owner has a font size, it should be used to convert. 

Specifically [here](https://github.com/wieslawsoltes/Svg.Skia/blob/master/src/Svg.Model/SvgModelExtensions.Transforms.cs#L20).

This should look something like
`if (owner?.FontSize.IsEmpty == false) {
  _deviceValue = owner.FontSize * value
}
else {// use current behavior}`

**Comment by wieslawsoltes** [comment]
Not yet supported.

**Comment by wieslawsoltes** [comment]
Fixed in #73
