### ISSUE TITLE
PNG image result does not match the SVG source.

### ISSUE THREAD

**Issue by bondarenkod** [wieslawsoltes/Svg.Skia#59]
Hi! 
I've come here from https://github.com/Redth/ResizetizerNT/issues/43 
I am not sure that the issue is related to this project for 100%, but I tried to run the viewer from the https://github.com/svg-net/SVG repository and it display the image without the difference from the original one. 

I have a few icons in the AdobeXD design. I exported them as the SVG files to use them in my project. Usually, everything is OK but not now. 
Instead of this result (as it is in the XD)
![ApplicationFrameHost_29_01_2021__22_44_07__e0926005-3114-45fe-be9e-ee741f1c7136](https://user-images.githubusercontent.com/3184414/106325438-8108af80-6283-11eb-8b5d-7df927374fa2.png) 
 images I see only the central icons without any background:

![explorer_29_01_2021__22_45_12__32993bbf-03e8-4377-a0d0-6631aa7a9bf2](https://user-images.githubusercontent.com/3184414/106325545-a695b900-6283-11eb-9e8b-4c88b192bb47.png)

After a short research I dig to the original svg-net/SVG project and run the Viewer:
![SVGViewer_29_01_2021__22_21_26__0679a4a5-acc2-4f1f-b734-39f3f2c3b5ac](https://user-images.githubusercontent.com/3184414/106325651-d5ac2a80-6283-11eb-8df1-b5559ca76dc7.png)

Then I tried to install and run the tool from the Windows Console:
 `Svg.Skia.Converter -f L:\src_github\ResizetizerNT\Resizetizer.NT.Tests\images\issue_43_0.svg -o "L:\"
 --format png`

Here is the result: 
![issue_43_0](https://user-images.githubusercontent.com/3184414/106325871-320f4a00-6284-11eb-8be7-596e2b1c6bfe.png) `(it's invisible on the light page)`
Here is the screenshot of the file: 
![explorer_29_01_2021__22_50_05__40397e26-7fd7-4694-ae05-335e2afb577a](https://user-images.githubusercontent.com/3184414/106326009-739ff500-6284-11eb-9709-ab858c9f0dc8.png)

I've also tried to run the code from .net console project, the result was the same. 
 `svg.Save("image.png", SKColors.Empty, SKEncodedImageFormat.Png, 100, 1f, 1f);`
` svg.Save("image.png", SKColors.Transparent, SKEncodedImageFormat.Png, 100, 1f, 1f);`
Only when I change the `background` color parameter from any transparent value
`svg.Save("image.png", SKColors.Green, SKEncodedImageFormat.Png, 100, 1f, 1f);`
I start getting a different result:
![image](https://user-images.githubusercontent.com/3184414/106326225-cc6f8d80-6284-11eb-93a4-d97576cfbd5f.png)

Could you help me with the issue? Should I go to the `svg-net/SVG` project and create an issue there? 

I pack all the SVG, including the XD file into this zip: 
[issue_43_0.zip](https://github.com/wieslawsoltes/Svg.Skia/files/5896288/issue_43_0.zip)

**Comment by wieslawsoltes** [comment]
It's bug in filter rendering.

**Comment by wieslawsoltes** [comment]
@bondarenkod I think I have fixed this issue. The fix is in the master branch right now. Will do NuGet release soon.

**Comment by wieslawsoltes** [comment]
This should be fixed in 0.5.7.1
