### ISSUE TITLE
font-weight of bold is not supported

### ISSUE THREAD

**Issue by benjaminZale** [wieslawsoltes/Svg.Skia#60]
The `font-weight` of bold is not supported.  For example the text "cat" From the [MDN text example](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text) did not have the font style applied.

**Comment by wieslawsoltes** [comment]
Fixed in https://github.com/wieslawsoltes/Svg.Skia/commit/683f81830a8b24e6c93afb27278314f15e85d054
