### ISSUE TITLE
Opacity only works for 0 and 1 for Image with SvgImage Source and Svg control

### ISSUE THREAD

**Issue by darinkes** [wieslawsoltes/Svg.Skia#62]
I noticed you can't fade away an Image with SvgImage Source.

Not sure if this is a limitation of Svg.Skia or Svg itself.

```xaml
<Style Selector="ContentPresenter">
  <Setter Property="Transitions">
    <Transitions>
      <DoubleTransition Property="Opacity" Duration="0:0:0.5" Easing="LinearEasing"/>
    </Transitions>
  </Setter>
</Style>
```

ContentPresenter includes a TextBlock and an Image. Only the TextBlock gets slowly invisible.
The Image only disapears as soon as Opacity becomes 0.0

**Comment by wieslawsoltes** [comment]
@darinkes Could you try with new `Svg` control:
https://github.com/wieslawsoltes/Svg.Skia/blob/706d968a28606bf90621df385b77b4608a91f1c5/samples/AvaloniaSvgSkiaSample/MainWindow.axaml#L22

**Comment by adossey** [comment]
I'm seeing the same behavior as @darinkes using both the Image and Svg controls in Avalonia.Svg.Skia version 0.10.6.1.

**Comment by wieslawsoltes** [comment]
This is an issue in AvaloniaUI with how opacity is blended when using custom draw operation

![rider64_bvo7LHrGJm](https://user-images.githubusercontent.com/2297442/121486119-23bf0080-c9d1-11eb-85ca-d6b5564e89c3.png)

**Comment by wieslawsoltes** [comment]
I have hack fix for that, but not really want it to use https://github.com/wieslawsoltes/Svg.Skia/pull/79

**Comment by adossey** [comment]
Thanks for the quick hack! I tried it out, and it works now when the Opacity is applied directly to the Svg control, but it still doesn't work when the Opacity is inherited from the parent control. I can work around this by just duplicating a little code, but inheriting the Opacity from the parent would certainly be ideal.

**Comment by wieslawsoltes** [comment]
> Thanks for the quick hack! I tried it out, and it works now when the Opacity is applied directly to the Svg control, but it still doesn't work when the Opacity is inherited from the parent control. I can work around this by just duplicating a little code, but inheriting the Opacity from the parent would certainly be ideal.

Without Avalonia fixing this in core library this hack is best I can do.

**Comment by darinkes** [comment]
@wieslawsoltes thanks for taking a look at it!

Should we open an issue at Avalonia?
May I ask you to do it, since you can be more specific what needs to be done?

**Comment by wieslawsoltes** [comment]
@darinkes It is know issue, not need to create new one
