### ISSUE TITLE
Move to svg-net organization?

### ISSUE THREAD

**Issue by mrbean-bremen** [wieslawsoltes/Svg.Skia#66]
This has been discussed while discussing the creation of svg-net. It would help to co-ordinate efforts, make the projects more visible, and use some of the additional features of organizations.

Technically, this would mean [transferring ownership](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository) to one of the admins of the organization, who in turn would make the current owner admin of the repo and the organization.
After the transfer, any URLs in the documentation pointing to the repository have to be adapted.
A redirect in GitHub will automatically be created.

cc @tebjan

(I have just done the same with a small repo of my own, so that reminded me...)

**Comment by mrbean-bremen** [comment]
This should have been a discussion, not an issue - closing and re-creating as discussion.

**Comment by wieslawsoltes** [comment]
> This should have been a discussion, not an issue - closing and re-creating as discussion.

I can transfer to discussion.

**Comment by mrbean-bremen** [comment]
Ok, sorry for the confusion - I already copied it to discussions. Moving would have been better of course... closing again, as now it's duplicated in discussions.
