### ISSUE TITLE
Memory Leak on DrawPath

### ISSUE THREAD

**Issue by radev8** [wieslawsoltes/Svg.Skia#70]
I am experiencing an issue which looks like a memory lean when I scale a SVG using a matrix. The sample application starts at about 70MB and then nearly doubles as you resize the app. The resize event triggers the redraw.

Steps to reproduce:

run the project
Resize the app and drag so the app is always resizing
I have attached a screenshot of the memory usage.

This project is a cut down version of a larger project which draws more objects and it grows by hundreds of megabytes by only resizing.

Taking snapshots was not that helpful as it said the app grew by a few bytes but it clearly grew by lots more.

Here is a copy of the sample app.
[Leak.zip](https://github.com/wieslawsoltes/Svg.Skia/files/6228451/Leak.zip)

I was previously using the SkiaSharp.Svg Version="1.60.0" library and was experiencing the same issue.

I would be interested in some guidance if this is my issue or something going on in the Svg.Skia Library.

**Comment by wieslawsoltes** [comment]
It's probably issue in SkiaSharp itself Svg.Skia is using SKPath same as SkiaSharp.Svg. All resource are disposed correctly during runtime.
