### ISSUE TITLE
Avalonia.Svg control gradient not working

### ISSUE THREAD

**Issue by tommaier123** [wieslawsoltes/Svg.Skia#75]
Hello,
I want to use the Avalonia control to show some svg images with gradients for example this [search bar](https://github.com/wieslawsoltes/Svg.Skia/files/6566994/searchbar.zip)
```<Svg Path="resm:NoodleManagerX.Assets.icons.searchbar.svg" Height="2" Width="200" Stretch="Fill"/>```
Instead of the gradient only the first color is used for the whole thing.
Is there a trick to get it to work?

Also another question, since installing the package the designer doesn't load anymore. Is there a way to make it work again?

**Comment by wieslawsoltes** [comment]
> Hello,
> I want to use the Avalonia control to show some svg images with gradients for example this [search bar](https://github.com/wieslawsoltes/Svg.Skia/files/6566994/searchbar.zip)
> `<Svg Path="resm:NoodleManagerX.Assets.icons.searchbar.svg" Height="2" Width="200" Stretch="Fill"/>`
> Instead of the gradient only the first color is used for the whole thing.
> Is there a trick to get it to work?

Currently `Avalonia.Svg.Skia` is recommended if you want best experience, `Avalonia.Svg` is under development and only supports really basic rendering.

> Also another question, since installing the package the designer doesn't load anymore. Is there a way to make it work again?

https://github.com/wieslawsoltes/Svg.Skia/blob/fbad254885790b3aaf9029b284bff03594d96814/samples/AvaloniaSvgSkiaSample/Program.cs#L15-L16

**Comment by tommaier123** [comment]
Awesome, thank you.
