### ISSUE TITLE
Embedded image in .SVG not rendered

### ISSUE THREAD

**Issue by esonhon** [wieslawsoltes/Svg.Skia#80]
Avalonia.svg 0.5.6.2 or nuget version 10.6.2, the embedded image in SVG file not rendered, just blank. And some single character not displayed.
Pls ref the attached SVG file and the render result in MS Edge of same file.
[Correct result in MS edge]
<img width="531" alt="svg_edge" src="https://user-images.githubusercontent.com/2252248/129430521-c369afea-0e95-428a-aea7-ac731b12defb.png">
[in AvaloniaSvgDemo]
<img width="668" alt="svg_avalonia_svg" src="https://user-images.githubusercontent.com/2252248/129430525-9a9242ab-2c13-49dd-9ed4-db2210042484.png">
[the svg file]
[_report_preview_.zip](https://github.com/wieslawsoltes/Svg.Skia/files/6985724/_report_preview_.zip)

**Comment by wieslawsoltes** [comment]
Please use `Avalonia.Svg.Skia` instead of `Avalonia.Svg`
