### ISSUE TITLE
paint-order not supported on path

### ISSUE THREAD

**Issue by Batboa** [wieslawsoltes/Svg.Skia#88]
Path does not seem to respect the `paint-order` attribute. Documentation [here](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/paint-order). I've not tested for other supported classes.

Here's an example SVG with the issue:  `data:image/svg+xml;charset=utf-8;base64,PHN2ZyBjbGFzcz0ibmNvbG9yZWQtc3ZnLWltYWdlIiB2aWV3Qm94PSI1MDAgMzkwIDIwMCAyMDAiIGhlaWdodD0iMzUwcHgiIHdpZHRoPSI0MDBweCIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4NCg0KPHBhdGggaWQ9InBhaW50T3JkZXIiIGZpbGwtcnVsZT0iZXZlbm9kZCIgZmlsbD0icmdiKDMsMCwwKSIgb3BhY2l0eT0iMSIgc3Ryb2tlLXdpZHRoPSIzMiIgZD0iTSA1NDUuMyA1MDMuMyBDIDU0OC43NTcgNTAzLjMgNTUxLjg3MiA1MDIuODQzIDU1NS4zIDUwMy43IEMgNTU4LjA1OCA1MTAuMTM2IDU1OC4zNjYgNTE4LjAyNyA1NjQuMiA1MjIuOCBDIDU2OS43MzEgNTI3LjMyNSA1ODIuNDY3IDUyNy44ODggNTgzLjggNTE5IEMgNTg0LjUxOSA1MTQuMjA2IDU4Mi43MjIgNTEwLjU4MSA1ODAuNCA1MDYuNiBDIDU3My42ODYgNDk1LjA5IDU1OS43ODcgNDkzLjQwNyA1NTEuNiA0ODMuNCBDIDU0NS4yNjEgNDc1LjY1MiA1NDQuMSA0NjQuNTk0IDU0NC4xIDQ1NSBDIDU0NC4xIDQ0OS4yOCA1NDMuNzk5IDQ0My42MDUgNTQ1LjIgNDM4IEMgNTQ5LjExNyA0MjIuMzMgNTYyLjc0NSA0MTAuMzAzIDU3OS41IDQxMS41IEMgNTg1LjkzOCA0MTEuOTYgNTkyLjMxMiA0MTUuOTg0IDU5Ny43IDQxOS4zIEMgNjAxLjI3NyA0MjEuNTAxIDYwMy40MzIgNDI0LjI1NCA2MDcuOCA0MjQuOCBDIDYwOS42OTUgNDIxLjk1NyA2MTAuNzg1IDQxOC41NzMgNjEyLjcgNDE1LjcgQyA2MTQuODkxIDQxNS4xNTIgNjE3LjEwOSA0MTUuMTUyIDYxOS4zIDQxNS43IEMgNjIwLjkzMSA0MjIuMjI2IDYyMC4zMjkgNDI4LjQyIDYyMCA0MzUgQyA2MTkuNjA2IDQ0Mi44NzUgNjIwLjc3OSA0NTAuOTcgNjE5LjggNDU4LjggQyA2MTYuNDc5IDQ2MS4wMTQgNjExLjk0OCA0NjEuMzc0IDYwOC40IDQ1OS42IEMgNjA1LjM1NSA0NTMuNTEgNjA2LjA1NSA0NDYuNDA5IDYwMC4zIDQ0MS43IEMgNTkzLjQ2OCA0MzYuMTEgNTgxLjYzNyA0NDAuNzQzIDU4Mi4xIDQ1MCBDIDU4Mi40NjIgNDU3LjIzMSA1ODkuMzE5IDQ2Mi43OTMgNTk1LjQgNDY1LjYgQyA2MDMuNDMzIDQ2OS4zMDcgNjEzLjAwMyA0NzQuNTE5IDYxNy42IDQ4Mi40IEMgNjIyLjYwNSA0OTAuOTgxIDYyNCA1MDAuMjEyIDYyNCA1MTAgQyA2MjQgNTE0LjIxOCA2MjQuNTI2IDUxOC44MjkgNjIzLjkgNTIzIEMgNjIyLjE1NCA1MzQuNjM4IDYxMy45NjkgNTQzLjUzMiA2MDQgNTQ4LjkgQyA2MDAuMDg4IDU1MS4wMDcgNTk1LjQ5NyA1NTIuNzc1IDU5MSA1NTMgQyA1ODIuMDE2IDU1My40NDkgNTczLjQ0NCA1NTAuNjI0IDU2NS42IDU0Ni40IEMgNTYyLjIxMyA1NDQuNTc2IDU2MC4wNTYgNTQxLjE2NCA1NTYuMiA1NDAuMiBDIDU1My4zNzcgNTQ0LjQzNCA1NTEuNDI2IDU1Mi4xMTMgNTQ0LjQgNTQ4LjYgQyA1NDIuNzIxIDUzOC41MjggNTQzLjEgNTI4LjE4OCA1NDMuMSA1MTggQyA1NDMuMSA1MTMuMDAyIDU0Mi4zNzkgNTA3LjY4MiA1NDUuMyA1MDMuMyIgc3Ryb2tlPSJyZ2IoMjU0LDIyMSwwKSIgc3Ryb2tlLWRhc2hhcnJheT0ibm9uZSIgcGFpbnQtb3JkZXI9InN0cm9rZSIvPg0KPC9zdmc+`

**Comment by wieslawsoltes** [comment]
SVG 2 features not planned
