### ISSUE TITLE
Get rid of System.Drawing.Common for Svg.Custom

### ISSUE THREAD

**Issue by Happypig375** [wieslawsoltes/Svg.Skia#92]
https://docs.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

Even though Svg.Skia should use SkiaSharp instead of System.Drawing.Common everywhere, System.Drawing.Common is still a dependency through Svg.Custom. It should not be used anymore.

**Comment by wieslawsoltes** [comment]
This library doesn't target only .NET 6
