### ISSUE TITLE
SvgVisualElement.Bounds disappeared between 0.5.10 and 0.5.11.1

### ISSUE THREAD

**Issue by KillyMXI** [wieslawsoltes/Svg.Skia#95]
Tried to update the package, got some of my code broken due to unavailability of `SvgVisualElement.Bounds`.
Seems like it might depend on `NO_SDC` flag in SVG.NET.

Is this intentional? I can't see what commit exactly caused this.

I'm currently depend on Svg.Skia and use whatever version of SVG.NET comes with it. Should I depend on both explicitly?

**Comment by wieslawsoltes** [comment]
Because Microsoft removed (disabled) cross-platform support for System.Drawing.Common the SVG.NET library is built for Svg.Skia without it. With .NET 7 System.Drawing.Common cross-platform support will be completely removed. Svg.Skia has model with bounds property. See the https://github.com/wieslawsoltes/Svg.Skia/discussions/93 discussion for how to access new bounds property.

**Comment by wieslawsoltes** [comment]
Please not the there is ongoing work to migrate from System.Drawing.Common but it's gigantic task.

**Comment by DevSelchow** [comment]
@wieslawsoltes Sry but from the linked discussion is still could not quite understand how to get the Bounds or the Drawable for a single SvgElement/SvgGroup. 
Could you expand you explanation a bit more?

**Comment by DevSelchow** [comment]
How do i get that for a element?
I have the model for my Drawing like 
`ShimSkiaSharp.SKPicture? Model = SvgExtensions.ToModel(svgDocument, AssetLoader, out var drawable, out var skBounds);`

but that does not work for elements
` ShimSkiaSharp.SKPicture? Model = SvgExtensions.ToModel(svgDocument.Children[0], AssetLoader, out var drawable, out var skBounds);
 `

**Comment by KillyMXI** [comment]
I need a way to measure text and maybe convert it to path.
Previously I could use `SvgVisualElement.Bounds` and  `SvgVisualElement.Path()`.

Couldn't keep kicking the can down the road anymore, has to figure this out at last.

Turns out the above suggestions were misleading for me.
Can't be angry because I never clarified my use case.

`TextDrawable` is useless in its current state - it only has `OwnerBounds` property as a kludge, any other bounds are not computed and stay at zero.

What I have to do is go down a layer and use `SKPaint`, something like this:

```csharp
using SKPaint paint = new()
{
    TextSize = 6, // height in pixels
    Typeface = SKTypeface.Default // SKTypeface.FromFamilyName(...)
};

SKRect measuredBounds = new();
_ = paint.MeasureText(text, ref measuredBounds);

SKPath path = paint.GetTextPath(text, 0, 0);
SvgPath svgPath = new SvgPath() {
    PathData = SvgPathBuilder.Parse(path.ToSvgPathData().AsSpan())
};
```
